-- ================================================
-- Messenger Schema Migration
-- Phase 1: Sendbird Migration
-- 
-- Run this script to create messenger tables:
--   mysql -u root -p bookofmormon < src/database/migrations/messenger_tables.sql
--
-- ID Strategy: YouTube-style 11-char base64url IDs (nanoid)
-- ================================================

-- Disable foreign key checks during creation
SET FOREIGN_KEY_CHECKS = 0;

-- 1. messenger_users - Messaging-specific user profile data
-- NOTE: No FK to bom_user due to charset mismatch (bom_user uses utf8, we use utf8mb4)
-- Referential integrity handled at application level
CREATE TABLE IF NOT EXISTS messenger_users (
  user_id VARCHAR(32) NOT NULL PRIMARY KEY COMMENT 'MD5 hash of bom_user.user',
  bom_user_id VARCHAR(256) NULL COMMENT 'Link to bom_user.user (nullable for bots)',
  nickname VARCHAR(100) NOT NULL,
  profile_url VARCHAR(512) DEFAULT '',
  metadata JSON DEFAULT NULL,
  is_bot BOOLEAN DEFAULT FALSE,
  is_online BOOLEAN DEFAULT FALSE,
  last_seen_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_bom_user_id (bom_user_id),
  INDEX idx_is_online (is_online)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. messenger_channels - Chat groups/channels
CREATE TABLE IF NOT EXISTS messenger_channels (
  channel_url VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'UUID or custom string',
  name VARCHAR(255) NOT NULL,
  cover_url VARCHAR(512) DEFAULT '',
  custom_type ENUM('private', 'public', 'open', 'solo', 'DM') NOT NULL DEFAULT 'private',
  description TEXT DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  lang VARCHAR(10) DEFAULT 'en',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_custom_type (custom_type),
  INDEX idx_lang (lang),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. messenger_members - Junction table for User-Channel membership
CREATE TABLE IF NOT EXISTS messenger_members (
  channel_url VARCHAR(255) NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  role ENUM('operator', 'member') NOT NULL DEFAULT 'member',
  state ENUM('joined', 'invited', 'requested') NOT NULL DEFAULT 'joined',
  is_muted BOOLEAN DEFAULT FALSE,
  last_read_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (channel_url, user_id),
  INDEX idx_user_id (user_id),
  INDEX idx_state (state),
  INDEX idx_last_read_at (last_read_at),
  CONSTRAINT fk_messenger_members_channel 
    FOREIGN KEY (channel_url) REFERENCES messenger_channels(channel_url) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messenger_members_user 
    FOREIGN KEY (user_id) REFERENCES messenger_users(user_id) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. messenger_messages - All message content
-- message_id: 11-char nanoid (YouTube-style), generated by application
CREATE TABLE IF NOT EXISTS messenger_messages (
  message_id VARCHAR(11) NOT NULL PRIMARY KEY COMMENT 'nanoid - YouTube-style ID',
  channel_url VARCHAR(255) NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  message_type ENUM('MESG', 'FILE', 'ADMN') NOT NULL DEFAULT 'MESG',
  message TEXT NOT NULL,
  custom_type VARCHAR(100) DEFAULT '',
  link_type VARCHAR(50) DEFAULT NULL COMMENT 'Type of linked content (scripture, person, place, etc)',
  link_target VARCHAR(255) DEFAULT NULL COMMENT 'Target identifier for linked content',
  link_aux VARCHAR(255) DEFAULT NULL COMMENT 'Auxiliary data for linked content',
  metadata JSON DEFAULT NULL COMMENT 'Arbitrary JSON for future extensibility (og:data, previews, etc)',
  parent_message_id VARCHAR(11) DEFAULT NULL COMMENT 'For threaded replies',
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_channel_url (channel_url),
  INDEX idx_user_id (user_id),
  INDEX idx_created_at (created_at),
  INDEX idx_message_type (message_type),
  INDEX idx_custom_type (custom_type),
  INDEX idx_parent_message_id (parent_message_id),
  INDEX idx_channel_created (channel_url, created_at),
  CONSTRAINT fk_messenger_messages_channel 
    FOREIGN KEY (channel_url) REFERENCES messenger_channels(channel_url) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messenger_messages_user 
    FOREIGN KEY (user_id) REFERENCES messenger_users(user_id) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messenger_messages_parent 
    FOREIGN KEY (parent_message_id) REFERENCES messenger_messages(message_id) 
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. messenger_highlights - Scripture highlights associated with messages
CREATE TABLE IF NOT EXISTS messenger_highlights (
  id VARCHAR(11) NOT NULL PRIMARY KEY COMMENT 'nanoid',
  message_id VARCHAR(11) NOT NULL,
  ordinal INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Order of highlight within message',
  text VARCHAR(1024) NOT NULL COMMENT 'Scripture reference or highlight text',
  INDEX idx_message_id (message_id),
  UNIQUE KEY uk_message_ordinal (message_id, ordinal),
  CONSTRAINT fk_messenger_highlights_message 
    FOREIGN KEY (message_id) REFERENCES messenger_messages(message_id) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. messenger_reactions - Emoji reactions
CREATE TABLE IF NOT EXISTS messenger_reactions (
  message_id VARCHAR(11) NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  reaction_key VARCHAR(50) NOT NULL COMMENT 'Emoji or reaction identifier',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id, user_id, reaction_key),
  INDEX idx_user_id (user_id),
  INDEX idx_reaction_key (reaction_key),
  CONSTRAINT fk_messenger_reactions_message 
    FOREIGN KEY (message_id) REFERENCES messenger_messages(message_id) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messenger_reactions_user 
    FOREIGN KEY (user_id) REFERENCES messenger_users(user_id) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. messenger_files - Metadata for uploaded assets
CREATE TABLE IF NOT EXISTS messenger_files (
  file_id VARCHAR(11) NOT NULL PRIMARY KEY COMMENT 'nanoid',
  message_id VARCHAR(11) DEFAULT NULL COMMENT 'Associated message, if any',
  user_id VARCHAR(32) NOT NULL COMMENT 'Uploader',
  file_url VARCHAR(1024) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) DEFAULT NULL COMMENT 'MIME type',
  file_size BIGINT UNSIGNED DEFAULT NULL COMMENT 'Size in bytes',
  thumbnail_url VARCHAR(1024) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_message_id (message_id),
  INDEX idx_user_id (user_id),
  INDEX idx_created_at (created_at),
  CONSTRAINT fk_messenger_files_message 
    FOREIGN KEY (message_id) REFERENCES messenger_messages(message_id) 
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_messenger_files_user 
    FOREIGN KEY (user_id) REFERENCES messenger_users(user_id) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- ================================================
-- Verification Queries
-- ================================================

-- Check tables exist
SELECT 'Verification: Tables created' AS status;
SHOW TABLES LIKE 'messenger_%';

-- Check foreign keys
SELECT 'Verification: Foreign keys' AS status;
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME LIKE 'messenger_%'
ORDER BY TABLE_NAME;

SELECT 'Migration complete!' AS status;
