import BomCapsulation from '../models/bom_capsulation';
import BomConnection from '../models/bom_connection';
import BomIndex from '../models/bom_index';
import BomDivision from '../models/bom_division';
import BomXtrasFax from '../models/bom_xtras_fax';
import BomXtrasFaxIndex from '../models/bom_xtras_fax_index';
import BomLabel from '../models/bom_label';
import BomLog from '../models/bom_log';
import BomLookup from '../models/bom_lookup';
import BomMapMove from '../models/bom_map_move';
import BomMapStory from '../models/bom_map_story';
import BomMapMovePeople from '../models/bom_map_move_people';
import BomMapMoveCoords from '../models/bom_map_move_coords';
import BomMap from '../models/bom_map';
import BomMarkdown from '../models/bom_markdown';
import BomNarration from '../models/bom_narration';
import BomPage from '../models/bom_page';
import BomPeopleRels from '../models/bom_people_rels';
import BomPeople from '../models/bom_people';
import BomPlacesCoords from '../models/bom_places_coords';
import BomPlaces from '../models/bom_places';
import BomQuote from '../models/bom_quote';
import BomReferences from '../models/bom_references';
import BomSection from '../models/bom_section';
import BomSectionrow from '../models/bom_sectionrow';
import BomShortlinks from '../models/bom_shortlinks';
import BomSlug from '../models/bom_slug';
import BomText from '../models/bom_text';
import BomTimeline from '../models/bom_timeline';
import BomTranslationLocked from '../models/bom_translation_locked';
import BomTranslation from '../models/bom_translation';
import BomUserHistory from '../models/bom_user_history';
import BomUserSocial from '../models/bom_user_social';
import BomUserToken from '../models/bom_user_token';
import BomUser from '../models/bom_user';
import BomXtrasSaractorsSim from '../models/bom_xtras_caractors_sim';
import BomXtrasCaractors from '../models/bom_xtras_caractors';
import BomXtrasCommentary from '../models/bom_xtras_commentary';
import BomXtrasImage from '../models/bom_xtras_image';
import BomXtrasSource from '../models/bom_xtras_source';
import BomXtrasStats from '../models/bom_xtras_stats';
import LdsScripturesBooks from '../models/lds_scriptures_books';
import LdsScripturesFootnotes from '../models/lds_scriptures_footnotes';
import LdsScripturesTranslations from '../models/lds_scriptures_translations';
import LdsScripturesVerses from '../models/lds_scriptures_verses';
import LdsScripturesVolumes from '../models/lds_scriptures_volumes';
import SocialPosts from '../models/social_posts';
import ModelBase from '../models/ModelBase';
import BomXtrasHistory from '../models/bom_xtras_history';
import BomXtrasChiasmus from '../models/bom_xtras_chiasmus';
import BoMDataBible from '../models/bom_bible';

export interface Models {
  BomCapsulation: typeof BomCapsulation;
  BoMDataBible: typeof BoMDataBible;
  BomConnection: typeof BomConnection;
  BomDivision: typeof BomDivision;
  BomIndex: typeof BomIndex;
  BomLabel: typeof BomLabel;
  BomLog: typeof BomLog;
  BomLookup: typeof BomLookup;
  BomMapMove: typeof BomMapMove;
  BomMapStory: typeof BomMapStory;
  BomMapMovePeople: typeof BomMapMovePeople;
  BomMapMoveCoords: typeof BomMapMoveCoords;
  BomMap: typeof BomMap;
  BomNarration: typeof BomNarration;
  BomMarkdown: typeof BomMarkdown;
  BomPage: typeof BomPage;
  BomPeopleRels: typeof BomPeopleRels;
  BomPeople: typeof BomPeople;
  BomPlacesCoords: typeof BomPlacesCoords;
  BomPlaces: typeof BomPlaces;
  BomQuote: typeof BomQuote;
  BomReferences: typeof BomReferences;
  BomSection: typeof BomSection;
  BomSectionrow: typeof BomSectionrow;
  BomShortlinks: typeof BomShortlinks;
  BomSlug: typeof BomSlug;
  BomText: typeof BomText;
  BomTimeline: typeof BomTimeline;
  BomTranslationLocked: typeof BomTranslationLocked;
  BomTranslation: typeof BomTranslation;
  BomUserSocial: typeof BomUserSocial;
  BomUserToken: typeof BomUserToken;
  BomUser: typeof BomUser;
  BomXtrasSaractorsSim: typeof BomXtrasSaractorsSim;
  BomXtrasCaractors: typeof BomXtrasCaractors;
  BomXtrasCommentary: typeof BomXtrasCommentary;
  BomXtrasFax: typeof BomXtrasFax;
  BomXtrasFaxIndex: typeof BomXtrasFaxIndex;
  BomXtrasImage: typeof BomXtrasImage;
  BomXtrasHistory: typeof BomXtrasHistory;
  BomXtrasChiasmus: typeof BomXtrasChiasmus;
  BomXtrasSource: typeof BomXtrasSource;
  BomXtrasStats: typeof BomXtrasStats;
  LdsScripturesBooks: typeof LdsScripturesBooks;
  LdsScripturesFootnotes: typeof LdsScripturesFootnotes;
  LdsScripturesTranslations: typeof LdsScripturesTranslations;
  LdsScripturesVerses: typeof LdsScripturesVerses;
  LdsScripturesVolumes: typeof LdsScripturesVolumes;
  SocialPosts: typeof SocialPosts;
  [key: string]: typeof ModelBase;
}
