/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface BomBot {
  bot_class: Generated<"community" | "study">;
  bot_id: string;
  created_at: Generated<Date>;
  display_name: string;
  enabled: Generated<number>;
  lang: string | null;
  model: string | null;
  persona: string | null;
  tags: Json | null;
  temperament: string | null;
  updated_at: Generated<Date>;
}

export interface BomBotRag {
  bot_id: string | null;
  channel_url: string | null;
  config: Json | null;
  created_at: Generated<Date>;
  enabled: Generated<number>;
  id: Generated<number>;
  resource_type: string;
  tag: string | null;
  updated_at: Generated<Date>;
  uri: string | null;
}

export interface BomBotSchedule {
  action: Generated<string>;
  cadence_minutes: number | null;
  channel_url: string;
  created_at: Generated<Date>;
  cron: string | null;
  enabled: Generated<number>;
  id: Generated<number>;
  last_run_at: Date | null;
  next_run_at: Date | null;
  updated_at: Generated<Date>;
}

export interface BomCache {
  content: Json;
  hash: string;
  key: string;
  timestamp: number;
}

export interface BomCapsulation {
  description: string;
  guid: string;
  link: string;
  parent: string;
  reference: string;
}

export interface BomConnection {
  guid: string;
  id: Generated<number>;
  link: string;
  parent: string;
  text: string;
  type: string;
}

export interface BomDataBible {
  bible_highlight: Json | null;
  bible_ref: string | null;
  bible_verse_id: number | null;
  bom_highlight: Json | null;
  bom_ref: string | null;
  bom_verse_id: number | null;
  guid: string;
  plus: number | null;
  quote: number | null;
  seq: number | null;
  similarity: number | null;
  src: string | null;
}

export interface BomDivision {
  description: string;
  guid: string;
  page: string;
  weight: number;
}

export interface BomIndex {
  guid: string | null;
  pkey: Generated<number>;
  ref: string;
  slug: string;
  text: string;
  type: string;
  verse_id: string;
  verse_id_end: string;
}

export interface BomLabel {
  guid: string;
  label_id: string;
  label_text: string;
  type: string | null;
}

export interface BomLog {
  credit: number;
  flag: number;
  id: Generated<number>;
  ip: string;
  timestamp: number;
  type: string;
  user: string;
  value: string;
}

export interface BomLogDuplicates {
  credit: number;
  flag: number;
  id: Generated<number>;
  ip: string;
  timestamp: number;
  type: string;
  user: string;
  value: string;
}

export interface BomLookup {
  id: Generated<number>;
  text_guid: string;
  verse_id: string;
}

export interface BomMap {
  centerx: number;
  centery: number;
  desc: string;
  group: string | null;
  guid: string;
  maxzoom: number;
  minzoom: number;
  name: string;
  priority: number;
  slug: string;
  tiles: Generated<number>;
  zoom: number;
}

export interface BomMapMove {
  description: string;
  duration: string | null;
  end: string;
  episode: string;
  guid: string;
  parent: string;
  ref: string;
  seq: number;
  start: string;
  travelers: string;
}

export interface BomMapMoveCoords {
  coords: Json;
  guid: string;
  map: string;
  segment_guid: string;
}

export interface BomMapMovePeople {
  people_slug: string;
  segment_guid: string;
}

export interface BomMapStory {
  description: string;
  guid: string;
  next: string | null;
  prev: string | null;
  slug: string;
  title: string;
}

export interface BomMarkdown {
  guid: string;
  markdown: string;
  slug: string;
}

export interface BomNarration {
  description: string;
  guid: string;
  parent: string;
  weight: number;
}

export interface BomObjects {
  aliases: string | null;
  category: string;
  description: string | null;
  era: string;
  guid: string;
  name: string;
  provenance: string;
  slug: string;
  specificity: string;
  subtitle: string | null;
  tags: string | null;
  usage: string;
  verse_id: number | null;
  weight: Generated<number>;
}

export interface BomPage {
  guid: string;
  parent: string;
  ref: string | null;
  title: string;
  weight: number;
}

export interface BomPeople {
  classification: string | null;
  date: string | null;
  description: string | null;
  guid: string | null;
  identification: string | null;
  name: string | null;
  slug: string;
  title: string | null;
  unit: string | null;
  verse_id: number | null;
  weight: number | null;
}

export interface BomPeopleRels {
  dst: string | null;
  dstrel: string | null;
  dstweight: Generated<number | null>;
  src: string | null;
  srcrel: string | null;
  srcweight: Generated<number | null>;
  strokewidth: number | null;
  uid: Generated<number>;
}

export interface BomPlaces {
  aka: string;
  ax: number;
  ay: number;
  description: string;
  guid: string;
  h: number;
  icon: string | null;
  info: string;
  label: string | null;
  location: string;
  name: string;
  occupants: string;
  slug: string;
  type: string;
  w: number;
  weight: number;
}

export interface BomPlacesCoords {
  guid: string;
  lat: string;
  lng: string;
  map: string;
  max: number | null;
  min: number | null;
  pkey: Generated<number>;
  slug: string | null;
  time: Date | null;
  user: string | null;
  zoom: number | null;
}

export interface BomPrdbomPeopleRels {
  dst: string | null;
  dstrel: string | null;
  dstweight: number | null;
  src: string | null;
  srcrel: string | null;
  srcweigh: number | null;
}

export interface BomQuote {
  guid: string;
  id: Generated<number>;
  parent: string;
}

export interface BomReadingplan {
  duedate: Date | null;
  guid: string | null;
  owner: string | null;
  slug: string | null;
  startdate: Date | null;
  title: string | null;
}

export interface BomReadingplanSeg {
  duedate: Date | null;
  end: number | null;
  guid: string | null;
  period: string | null;
  plan: string | null;
  ref: string | null;
  sectionGuids: string | null;
  start: number | null;
  title: string | null;
}

export interface BomReferences {
  block: number;
  id: Generated<number>;
  page: string;
  ref: string;
}

export interface BomSection {
  ambient: string | null;
  badge: string;
  guid: string;
  parent: string;
  ref: string;
  title: string;
  weight: number;
}

export interface BomSectionrow {
  guid: string;
  parent: string;
  type: string;
  weight: number;
}

export interface BomShortlinks {
  hash: Generated<string>;
  string: string | null;
}

export interface BomSlug {
  guid: string;
  id: Generated<number>;
  link: string;
  parent: string;
  slug: string;
  type: string;
}

export interface BomText {
  chrono: string | null;
  content: string | null;
  duration: number | null;
  guid: string;
  heading: string | null;
  index_code: string | null;
  link: number | null;
  min_verse_id: number | null;
  page: string | null;
  parent: string | null;
  parentLink: number | null;
  queue_weight: string | null;
  ref: Generated<number | null>;
  section: string | null;
  weight: number | null;
}

export interface BomTimeline {
  date: string;
  file: string;
  grid_bg: string | null;
  grid_col: number | null;
  grid_h: number | null;
  grid_row: number | null;
  grid_w: number | null;
  h: number;
  heading: string;
  html: string;
  id: string;
  label_category: "event" | "people" | "place" | null;
  narr: string;
  o: number;
  p: Generated<number>;
  reference: string;
  slug: string | null;
  w: number;
  x: number;
  y: number;
  z: Generated<number>;
}

export interface BomTranslation {
  auditor: Generated<string>;
  contributor: Generated<string>;
  guid: Generated<string>;
  id: Generated<number>;
  lang: Generated<string>;
  prev_value: string | null;
  refkey: Generated<string>;
  score: number | null;
  time: Generated<Date>;
  value: string;
}

export interface BomTranslationLocked {
  guid: string;
  lang: string;
  time: string;
  user: string;
}

export interface BomUser {
  complete: Generated<Decimal | null>;
  count: number | null;
  created_at: Date | null;
  dnc: number | null;
  email: string | null;
  finished: Generated<number | null>;
  first: number | null;
  lang: string | null;
  last_active: number | null;
  name: string | null;
  pass: string;
  started: Generated<Decimal | null>;
  time: Generated<number | null>;
  user: string;
  visibility: string | null;
  zip: string | null;
}

export interface BomUserMeta {
  active_group: string | null;
  bookmark: Json | null;
  metadata: Json | null;
  updated_at: Generated<Date | null>;
  user: string;
}

export interface BomUserSocial {
  id: Generated<number>;
  network: string;
  social_id: string;
  user: string;
}

export interface BomUserToken {
  token: string;
  usage: Generated<string | null>;
  user: string;
}

export interface BomVirtualgroupPrompts {
  bot_id: string | null;
  group_id: string;
  guid: string;
  lang: string;
  prompt: string | null;
  reference: string;
  thread_id: string | null;
}

export interface BomXrels {
  dst_slug: string;
  dst_type: string;
  note: string | null;
  rel: string;
  src_slug: string;
  src_type: string;
  srcweight: Generated<number | null>;
  uid: Generated<number>;
}

export interface BomXtrasAudio {
  album: string;
  artist: string;
  caption: string;
  file: string;
  id: Generated<number>;
  link: string;
  lyrics: string;
  placed: Generated<number>;
  ref: string;
  title: string;
}

export interface BomXtrasCaractors {
  char: number;
  id: string;
  match: string;
  row: number;
}

export interface BomXtrasCaractorsSim {
  id: Generated<number>;
  match: string;
  sim: string;
}

export interface BomXtrasChiasmus {
  chiasmus_id: string | null;
  guid: string | null;
  highlights: string | null;
  i: number | null;
  label: string | null;
  line_key: string | null;
  line_text: string | null;
  title: string | null;
  verse_id: number | null;
  verses: number | null;
}

export interface BomXtrasCommentary {
  id: number;
  is_note: Generated<number>;
  length: number;
  location_guid: string;
  old_id: number | null;
  source: string;
  text: string;
  title: string;
  verse_id: number | null;
  verse_range: Generated<number>;
}

export interface BomXtrasDictionary {
  _word: string;
  content: string;
  heading: string;
  id: Generated<number>;
  length: number | null;
  string: string | null;
  word: string | null;
}

export interface BomXtrasFax {
  bgcolor: string | null;
  code: string | null;
  com: Generated<number | null>;
  fax: number;
  format: string;
  hide: Generated<number>;
  indexRef: string | null;
  info: string | null;
  lang: Generated<string>;
  pages: number | null;
  pgfirstVerse: number | null;
  pgoffset: number | null;
  slug: Generated<string>;
  title: string | null;
  weight: number;
}

export interface BomXtrasFaxIndex {
  BRH: number;
  BRW: number;
  H: number;
  page: number;
  pageScale: number;
  pageWidth: number;
  TLH: number;
  TLW: number;
  uid: Generated<number>;
  verse_id: string;
  version: string;
  W: number;
  X: number;
  Y: number;
}

export interface BomXtrasHistory {
  archive: string | null;
  archive_id: string | null;
  aspect: number | null;
  author: string | null;
  citation: string | null;
  date: string | null;
  document: string | null;
  event_date: string | null;
  event_year: number | null;
  guid: string | null;
  id: number | null;
  language: Generated<string | null>;
  link: string | null;
  metadata: Json | null;
  pages: number | null;
  principal: string | null;
  repository: string | null;
  seq: number;
  slug: string;
  source: string | null;
  teaser: string | null;
  transcript: string | null;
  type: string | null;
  year: number | null;
}

export interface BomXtrasImage {
  artist: string;
  file: string;
  height: Generated<number>;
  id: Generated<number>;
  link: string;
  location_guid: string | null;
  title: string;
  width: Generated<number>;
}

export interface BomXtrasSource {
  excerpt: Generated<number | null>;
  item_count: number | null;
  source_description: string | null;
  source_id: number;
  source_lang: string | null;
  source_name: string;
  source_publisher: string | null;
  source_rating: string;
  source_short: string;
  source_slug: string;
  source_title: string;
  source_url: string;
  source_year: number | null;
}

export interface BomXtrasStats {
  id: Generated<number>;
  ip: string;
  key: string;
  timestamp: number;
  user: string;
  value: string;
}

export interface BomXtrasVideo {
  file: string;
  h: number;
  id: Generated<number>;
  link: string;
  owner: string;
  ref: string;
  title: string;
  w: number;
}

export interface LabelTranslations {
  de: string | null;
  en: string | null;
  eo: string | null;
  es: string | null;
  fr: string | null;
  guid: string;
  jp: string | null;
  ko: string | null;
  pt: string | null;
  ru: string | null;
  swe: string | null;
  tgl: string | null;
  vn: string | null;
}

export interface LdsScripturesBooks {
  bg: string | null;
  book_id: Generated<number>;
  book_subtitle: Generated<string>;
  book_title: Generated<string>;
  book_title_jst: Generated<string>;
  book_title_long: Generated<string>;
  book_title_med: string;
  book_title_short: Generated<string>;
  lds_org: Generated<string>;
  num_chapters: Generated<number>;
  num_verses: Generated<number>;
  volume_id: Generated<number>;
}

export interface LdsScripturesCrossref {
  dst_ref: string;
  dst_verse_id: number;
  match: number;
  notes: string;
  significant: Generated<number>;
  source: string;
  src_ref: string;
  src_verse_id: number;
  standin: Generated<number>;
  type: string;
}

export interface LdsScripturesFootnotes {
  book: string;
  chapter: string;
  guid: string;
  note: string;
  reference: string;
  verse: string;
  volume: string;
}

export interface LdsScripturesHeadings {
  lang: string;
  text: string | null;
  verse_id: number;
  version: string;
}

export interface LdsScripturesLines {
  format: string | null;
  guid: string;
  line_num: number | null;
  person_slug: string | null;
  text: string | null;
  verse_id: number | null;
  voice: string | null;
}

export interface LdsScripturesMeta {
  book_id: Generated<number | null>;
  footer: Generated<number>;
  id: string;
  level: Generated<number | null>;
  prev_id: string | null;
  seq: number | null;
  style: Generated<string>;
  text: string;
  type: string;
  verse_id: number;
  version: string;
}

export interface LdsScripturesTranslations {
  book: string;
  book_id: number;
  chapter: number;
  id: Generated<number>;
  lang: string;
  text: string;
  verse: number;
  verse_id: number;
}

export interface LdsScripturesVerses {
  book_id: Generated<number>;
  chapter: Generated<number>;
  pilcrow: Generated<number>;
  verse: Generated<number>;
  verse_id: Generated<number>;
  verse_scripture: string;
  verse_title: Generated<string>;
  verse_title_short: Generated<string>;
  volume_id: Generated<number>;
}

export interface LdsScripturesVolumes {
  lds_org: Generated<string>;
  num_books: Generated<number>;
  num_chapters: Generated<number>;
  num_verses: Generated<number>;
  volume_id: Generated<number>;
  volume_subtitle: Generated<string>;
  volume_title: Generated<string>;
  volume_title_long: Generated<string>;
  volume_title_med: string;
  volume_title_short: string;
}

export interface MessengerChannels {
  /**
   * UUID or custom string
   */
  channel_url: string;
  cover_url: Generated<string | null>;
  created_at: Generated<Date | null>;
  custom_type: Generated<"DM" | "open" | "private" | "public" | "solo">;
  description: string | null;
  lang: Generated<string | null>;
  metadata: Json | null;
  name: string;
  updated_at: Generated<Date | null>;
}

export interface MessengerFiles {
  created_at: Generated<Date | null>;
  /**
   * nanoid
   */
  file_id: string;
  file_name: string;
  /**
   * Size in bytes
   */
  file_size: number | null;
  /**
   * MIME type
   */
  file_type: string | null;
  file_url: string;
  /**
   * Associated message, if any
   */
  message_id: string | null;
  metadata: Json | null;
  thumbnail_url: string | null;
  /**
   * Uploader
   */
  user_id: string;
}

export interface MessengerHighlights {
  /**
   * nanoid
   */
  id: string;
  message_id: string;
  /**
   * Order of highlight within message
   */
  ordinal: Generated<number>;
  /**
   * Scripture reference or highlight text
   */
  text: string;
}

export interface MessengerMembers {
  channel_url: string;
  created_at: Generated<Date | null>;
  is_muted: Generated<number | null>;
  last_read_at: Date | null;
  role: Generated<"member" | "operator">;
  state: Generated<"banned" | "invited" | "joined" | "requested">;
  updated_at: Generated<Date | null>;
  user_id: string;
}

export interface MessengerMessages {
  channel_url: string;
  created_at: Generated<Date | null>;
  custom_type: Generated<string | null>;
  is_deleted: Generated<number | null>;
  /**
   * Auxiliary data for linked content
   */
  link_aux: string | null;
  /**
   * Target identifier for linked content
   */
  link_target: string | null;
  /**
   * Type of linked content (scripture, person, place, etc)
   */
  link_type: string | null;
  message: string;
  /**
   * nanoid - YouTube-style ID
   */
  message_id: string;
  message_type: Generated<"ADMN" | "FILE" | "MESG">;
  /**
   * Arbitrary JSON for future extensibility (og:data, previews, etc)
   */
  metadata: Json | null;
  /**
   * For threaded replies
   */
  parent_message_id: string | null;
  updated_at: Generated<Date | null>;
  user_id: string;
}

export interface MessengerReactions {
  created_at: Generated<Date | null>;
  message_id: string;
  /**
   * Emoji or reaction identifier
   */
  reaction_key: string;
  user_id: string;
}

export interface MessengerUsers {
  /**
   * Link to bom_user.user (nullable for bots)
   */
  bom_user_id: string | null;
  created_at: Generated<Date | null>;
  is_bot: Generated<number | null>;
  is_online: Generated<number | null>;
  last_seen_at: Date | null;
  metadata: Json | null;
  nickname: string;
  profile_url: Generated<string | null>;
  updated_at: Generated<Date | null>;
  /**
   * MD5 hash of bom_user.user
   */
  user_id: string;
}

export interface SocialPosts {
  facebook: string;
  id: number;
  link: string;
  parent: Generated<string>;
  twitter: string;
  type: string;
}

export interface DB {
  bom_bot: BomBot;
  bom_bot_rag: BomBotRag;
  bom_bot_schedule: BomBotSchedule;
  bom_cache: BomCache;
  bom_capsulation: BomCapsulation;
  bom_connection: BomConnection;
  bom_data_bible: BomDataBible;
  bom_division: BomDivision;
  bom_index: BomIndex;
  bom_label: BomLabel;
  bom_log: BomLog;
  bom_log_duplicates: BomLogDuplicates;
  bom_lookup: BomLookup;
  bom_map: BomMap;
  bom_map_move: BomMapMove;
  bom_map_move_coords: BomMapMoveCoords;
  bom_map_move_people: BomMapMovePeople;
  bom_map_story: BomMapStory;
  bom_markdown: BomMarkdown;
  bom_narration: BomNarration;
  bom_objects: BomObjects;
  bom_page: BomPage;
  bom_people: BomPeople;
  bom_people_rels: BomPeopleRels;
  bom_places: BomPlaces;
  bom_places_coords: BomPlacesCoords;
  bom_prdbom_people_rels: BomPrdbomPeopleRels;
  bom_quote: BomQuote;
  bom_readingplan: BomReadingplan;
  bom_readingplan_seg: BomReadingplanSeg;
  bom_references: BomReferences;
  bom_section: BomSection;
  bom_sectionrow: BomSectionrow;
  bom_shortlinks: BomShortlinks;
  bom_slug: BomSlug;
  bom_text: BomText;
  bom_timeline: BomTimeline;
  bom_translation: BomTranslation;
  bom_translation_locked: BomTranslationLocked;
  bom_user: BomUser;
  bom_user_meta: BomUserMeta;
  bom_user_social: BomUserSocial;
  bom_user_token: BomUserToken;
  bom_virtualgroup_prompts: BomVirtualgroupPrompts;
  bom_xrels: BomXrels;
  bom_xtras_audio: BomXtrasAudio;
  bom_xtras_caractors: BomXtrasCaractors;
  bom_xtras_caractors_sim: BomXtrasCaractorsSim;
  bom_xtras_chiasmus: BomXtrasChiasmus;
  bom_xtras_commentary: BomXtrasCommentary;
  bom_xtras_dictionary: BomXtrasDictionary;
  bom_xtras_fax: BomXtrasFax;
  bom_xtras_fax_index: BomXtrasFaxIndex;
  bom_xtras_history: BomXtrasHistory;
  bom_xtras_image: BomXtrasImage;
  bom_xtras_source: BomXtrasSource;
  bom_xtras_stats: BomXtrasStats;
  bom_xtras_video: BomXtrasVideo;
  label_translations: LabelTranslations;
  lds_scriptures_books: LdsScripturesBooks;
  lds_scriptures_crossref: LdsScripturesCrossref;
  lds_scriptures_footnotes: LdsScripturesFootnotes;
  lds_scriptures_headings: LdsScripturesHeadings;
  lds_scriptures_lines: LdsScripturesLines;
  lds_scriptures_meta: LdsScripturesMeta;
  lds_scriptures_translations: LdsScripturesTranslations;
  lds_scriptures_verses: LdsScripturesVerses;
  lds_scriptures_volumes: LdsScripturesVolumes;
  messenger_channels: MessengerChannels;
  messenger_files: MessengerFiles;
  messenger_highlights: MessengerHighlights;
  messenger_members: MessengerMembers;
  messenger_messages: MessengerMessages;
  messenger_reactions: MessengerReactions;
  messenger_users: MessengerUsers;
  social_posts: SocialPosts;
}
