/**
 * Structured onomasticon of Book of Mormon proper names.
 *
 * Each entry maps a name to:
 *  - types:    person | place | object | animal | plant | measure | material | title | word
 *  - cultures: people-affiliations (Nephite, Lamanite, Jaredite, Mulekite, Israelite)
 *              and/or proposed language origins (Hebrew, Egyptian, Greek, Akkadian)
 *  - morphology: prefix / stems / affix / suffix — a heuristic surface segmentation
 *    chosen so that names sharing an element share a tag (e.g. Mormon, Moroni,
 *    Morianton all carry stem "Mor"). This is a filtering aid, NOT established
 *    etymology. `note` flags glosses given in the text itself and etymology
 *    proposals from published onomastic work (cf. the BYU Book of Mormon
 *    Onomasticon project); "prop." and "cf." mark the speculative ones.
 *
 * Name list validated against the platform's canonical people/places data
 * (bom_people / bom_places via GraphQL). Person/place types and affiliations
 * come from that data; objects, measures, animals, and words are tagged by
 * their source passages (money: Alma 11; curelom/cumom: Ether 9:19; etc.).
 * See docs/reference/bom-names-dataset.md for list-cleanup decisions.
 */

const n = (name, types, cultures, prefix, stems, affix, suffix, note) => ({
  name,
  types: types.split("|"),
  cultures: cultures.split("|"),
  prefix: prefix || null,
  stems,
  affix: affix || null,
  suffix: suffix || null,
  note: note || null,
});

const names = [
  n("Abinadi", "person", "Nephite|Hebrew", "", ["Abinad"], "", "~i", "prop. Heb. ʾābī 'my father' element"),
  n("Abinadom", "person", "Nephite|Hebrew", "", ["Abinad"], "", "~om"),
  n("Abish", "person", "Lamanite|Hebrew", "", ["Abish"], "", "", "prop. Heb. ʾabī 'my father' element"),
  n("Ablom", "place", "Jaredite", "", ["Abl"], "", "~om"),
  n("Agosh", "place", "Jaredite", "", ["Agosh"], "", "", "plains of Agosh (Ether 14:15)"),
  n("Aha", "person", "Nephite|Egyptian", "", ["Aha"], "", "", "cf. Eg. ʿḥꜣ 'warrior'"),
  n("Ahah", "person", "Jaredite", "", ["Aha"], "", "~h"),
  n("Akish", "person|place", "Jaredite", "A~", ["Kish"], "", "", "cf. Philistine Achish (1 Sam 27); also wilderness of Akish"),
  n("Alma", "person|place", "Nephite|Hebrew", "", ["Alma"], "", "", "attested as Semitic male name ʾlmʾ in a 2nd-c. AD Judean deed"),
  n("Amaleki", "person", "Nephite|Hebrew", "", ["Amalek"], "", "~i", "cf. bibl. Amalek"),
  n("Amalickiah", "person", "Nephite|Lamanite|Hebrew", "", ["Amalek"], "", "~iah"),
  n("Amaron", "person", "Nephite", "Am~", ["Aron"], "", "", "prop. Am~ + Aaron-type element"),
  n("Amgid", "person", "Jaredite", "Am~", ["Gid"], "", ""),
  n("Aminadab", "person", "Nephite|Lamanite|Hebrew", "", ["Aminad"], "", "~ab", "bibl. Amminadab (Ex 6:23)"),
  n("Aminadi", "person", "Nephite|Hebrew", "", ["Aminad"], "", "~i"),
  n("Amlici", "person", "Nephite", "", ["Amlic"], "", "~i", "poss. rel. Amaleki / Amalickiah"),
  n("Ammah", "person", "Nephite", "", ["Ammah"], "", ""),
  n("Ammaron", "person", "Nephite", "Am~", ["Aron"], "", "", "record-keeper (4 Ne); cf. Amaron"),
  n("Ammon", "person", "Nephite|Mulekite|Egyptian", "", ["Ammon"], "", "", "cf. Eg. Amun; bibl. ʿAmmōn"),
  n("Ammonihah", "person|place", "Nephite|Egyptian", "", ["Ammon"], "", "~ihah"),
  n("Ammoron", "person", "Nephite", "Am~", ["Mor"], "", "~on"),
  n("Amnigaddah", "person", "Jaredite", "", ["Amni", "Gad"], "", "~ah"),
  n("Amnihu", "place", "Nephite", "", ["Amni"], "", "~hu", "hill east of the Sidon (Alma 2:15)"),
  n("Amnor", "person|measure", "Nephite", "", ["Amn"], "", "~or", "Nephite spy (Alma 2:22); also a silver measure (Alma 11)"),
  n("Amoron", "person", "Nephite", "Am~", ["Mor"], "", "~on"),
  n("Amulek", "person", "Nephite", "A~", ["Mul"], "", "~ek", "prop. A~ + Mulek"),
  n("Amulon", "person|place", "Nephite|Lamanite", "A~", ["Mul"], "", "~on", "priest of Noah; land of Amulon"),
  n("Angola", "place", "Nephite", "", ["Angol"], "", "~a"),
  n("Ani-Anti", "place", "Lamanite", "", ["Ani", "Ant"], "", "~i"),
  n("Antiomno", "person", "Lamanite", "", ["Anti"], "~omn~", "~o"),
  n("Antion", "measure", "Nephite", "", ["Anti"], "", "~on", "gold measure (Alma 11:19)"),
  n("Antionah", "person", "Nephite", "", ["Anti"], "~on~", "~ah"),
  n("Antionum", "person|place", "Nephite", "", ["Anti"], "~on~", "~um", "also the Zoramite land (Alma 31:3)"),
  n("Antiparah", "place", "Nephite", "", ["Anti"], "~par~", "~ah"),
  n("Antipus", "person", "Nephite|Greek", "", ["Anti"], "", "~pus", "Greek-looking; cf. Antipas"),
  n("Antum", "place", "Nephite", "", ["Ant"], "", "~um"),
  n("Archeantus", "person", "Nephite|Greek", "", ["Arche", "Ant"], "", "~us", "Greek-looking arche- 'chief'"),
  n("Cezoram", "person", "Nephite", "Se~", ["Zoram"], "", "", "C-spelling; cf. Seezoram"),
  n("Chemish", "person", "Nephite|Hebrew", "", ["Chemish"], "", "", "cf. Moabite deity Chemosh"),
  n("Cohor", "person", "Jaredite", "", ["Co", "Hor"], "", "", "cf. Corihor"),
  n("Com", "person", "Jaredite", "", ["Com"], "", ""),
  n("Comnor", "place", "Jaredite", "", ["Com"], "", "~nor", "hill Comnor (Ether 14:28)"),
  n("Corianton", "person", "Nephite", "", ["Cor"], "~iant~", "~on"),
  n("Coriantor", "person", "Jaredite", "", ["Cor"], "~iant~", "~or"),
  n("Coriantum", "person", "Jaredite", "", ["Cor"], "~iant~", "~um"),
  n("Coriantumr", "person", "Jaredite|Mulekite", "", ["Cor"], "~iant~", "~umr", "last Jaredite king; also a Mulekite-line Nephite dissenter (Hel 1)"),
  n("Corihor", "person|place", "Jaredite|Egyptian", "", ["Cor", "Hor"], "~i~", "", "cf. Eg. Herihor; land and valley of Corihor"),
  n("Corom", "person", "Jaredite", "", ["Cor"], "", "~om"),
  n("Cumeni", "place", "Nephite", "", ["Cumen"], "", "~i"),
  n("Cumenihah", "person", "Nephite", "", ["Cumen"], "", "~ihah"),
  n("Cumom", "animal", "Jaredite", "", ["Cum"], "", "~om", "unidentified animal (Ether 9:19)"),
  n("Cumorah", "place", "Nephite", "", ["Cum"], "", "~orah", "Jaredite name of the same hill: Ramah"),
  n("Curelom", "animal", "Jaredite", "", ["Curel"], "", "~om", "unidentified animal (Ether 9:19)"),
  n("Deseret", "word", "Jaredite|Egyptian", "", ["Deseret"], "", "", "glossed 'honey bee' (Ether 2:3); cf. Eg. dšrt"),
  n("Emer", "person", "Jaredite", "", ["Em"], "", "~er"),
  n("Emron", "person", "Nephite", "", ["Em"], "~r~", "~on", "fallen soldier (Moro 9:2)"),
  n("Enos", "person", "Nephite|Hebrew", "", ["Enos"], "", "", "Heb. ʾĕnôš 'man' (Gen 4:26)"),
  n("Esrom", "person", "Jaredite", "", ["Es"], "~r~", "~om", "cf. bibl. Esrom/Hezron"),
  n("Ethem", "person", "Jaredite", "", ["Eth"], "", "~em"),
  n("Ether", "person", "Jaredite", "", ["Eth"], "", "~er"),
  n("Ezias", "person", "Israelite|Hebrew", "", ["Ez"], "", "~ias", "brass-plates prophet; cf. Esaias"),
  n("Ezrom", "measure", "Nephite", "", ["Ez"], "~r~", "~om", "silver measure (Alma 11)"),
  n("Gadiandi", "place", "Nephite", "", ["Gad"], "~iand~", "~i"),
  n("Gadianton", "person", "Nephite", "", ["Gad"], "~iant~", "~on", "robber founder; shares ~iant~ with Coriantumr family"),
  n("Gadiomnah", "place", "Nephite", "", ["Gad"], "~iomn~", "~ah"),
  n("Gazelem", "person|object", "Nephite", "", ["Gazel"], "", "~em", "name of a servant / seer stone (Alma 37:23)"),
  n("Gid", "person|place", "Nephite|Hebrew", "", ["Gid"], "", "", "cf. Heb. gd 'fortune' (Gad, Gideon)"),
  n("Giddianhi", "person", "Nephite", "", ["Gid"], "~ian~", "~hi", "robber chief (3 Ne 3)"),
  n("Giddonah", "person", "Nephite", "", ["Gid"], "", "~onah"),
  n("Gideon", "person|place", "Nephite|Hebrew", "", ["Gid"], "", "~eon", "bibl. Gideon (Judg 6)"),
  n("Gidgiddonah", "person", "Nephite", "", ["Gid", "Gid"], "", "~onah", "reduplicated Gid"),
  n("Gidgiddoni", "person", "Nephite", "", ["Gid", "Gid"], "", "~oni", "reduplicated Gid"),
  n("Gilgah", "person", "Jaredite", "", ["Gil"], "", "~gah"),
  n("Gilgal", "person|place", "Nephite|Hebrew", "", ["Gil"], "", "~gal", "bibl. Gilgal 'circle (of stones)'"),
  n("Gimgimno", "place", "Nephite", "", ["Gim", "Gim"], "", "~no", "reduplication, like Gidgiddoni"),
  n("Hagoth", "person", "Nephite|Hebrew", "", ["Hag"], "", "~oth", "shipbuilder; cf. Heb. Haggith/Haggai (ḥag 'feast')"),
  n("Hearthom", "person", "Jaredite", "", ["Hearth"], "", "~om"),
  n("Helam", "person|place", "Nephite|Hebrew", "", ["Hel"], "", "~am", "cf. bibl. Helam (2 Sam 10:16)"),
  n("Helaman", "person", "Nephite", "", ["Hel"], "~am~", "~an"),
  n("Helem", "person", "Nephite|Hebrew", "", ["Hel"], "", "~em", "cf. bibl. Helem (1 Chr 7:35)"),
  n("Helorum", "person", "Nephite", "", ["Hel"], "~or~", "~um"),
  n("Hem", "person", "Nephite|Egyptian", "", ["Hem"], "", "", "cf. Eg. ḥm 'servant'"),
  n("Hermounts", "place", "Nephite|Egyptian", "", ["Hermounts"], "", "", "wild-beast wilderness; prop. cf. Eg. Hermonthis (Montu)"),
  n("Heshlon", "place", "Jaredite", "", ["Hesh"], "", "~lon", "plains of Heshlon (Ether 13:28)"),
  n("Heth", "person|place", "Jaredite|Hebrew", "", ["Heth"], "", "", "bibl. Heth (Gen 10:15)"),
  n("Himni", "person", "Nephite", "", ["Him"], "", "~ni"),
  n("Irreantum", "place", "Nephite", "", ["Irr"], "~eant~", "~um", "glossed 'many waters' (1 Ne 17:5)"),
  n("Isabel", "person", "Nephite|Hebrew", "", ["Isabel"], "", "", "cf. Jezebel (ʾĪzeḇel)"),
  n("Jacobugath", "place", "Nephite|Hebrew", "", ["Jacob", "Gath"], "~u~", "", "city of king Jacob's followers; Heb. gat 'winepress'"),
  n("Jacom", "person", "Jaredite", "", ["Jac"], "", "~om", "prop. cf. Jacob"),
  n("Jared", "person", "Jaredite|Hebrew", "", ["Jared"], "", "", "bibl. Jared (Gen 5:15)"),
  n("Jarom", "person", "Nephite|Hebrew", "", ["Jar"], "", "~om", "prop. Heb. yārōm 'may he be exalted'"),
  n("Jashon", "place", "Nephite", "", ["Jash"], "", "~on", "city and land (Morm 2:16)"),
  n("Jeneum", "person", "Nephite", "", ["Jene"], "", "~um", "commander (Morm 6:14)"),
  n("Jershon", "place", "Nephite|Hebrew", "", ["Jersh"], "", "~on", "Heb. yrš 'to inherit' + -ôn — the 'land of inheritance' (Alma 27:22)"),
  n("Josh", "person|place", "Nephite|Hebrew", "", ["Josh"], "", "", "cf. short form of Josiah/Joshua"),
  n("Kib", "person", "Jaredite", "", ["Kib"], "", ""),
  n("Kim", "person", "Jaredite", "", ["Kim"], "", ""),
  n("Kimnor", "person", "Jaredite", "", ["Kim"], "", "~nor"),
  n("Kish", "person", "Jaredite|Hebrew", "", ["Kish"], "", "", "bibl. Kish, father of Saul"),
  n("Kishkumen", "person|place", "Nephite", "", ["Kish", "Cumen"], "", "", "robber; also a city (3 Ne 9:10)"),
  n("Korihor", "person", "Nephite|Egyptian", "", ["Kor", "Hor"], "~i~", "", "cf. Eg. Herihor; K-spelling of Corihor"),
  n("Kumen", "person", "Nephite", "", ["Cumen"], "", "", "disciple (3 Ne 19:4); K-spelling of the cumen element"),
  n("Kumenonhi", "person", "Nephite", "", ["Cumen"], "~on~", "~hi", "disciple (3 Ne 19:4)"),
  n("Laban", "person", "Israelite|Hebrew", "", ["Laban"], "", "", "Heb. lābān 'white'"),
  n("Lachoneus", "person", "Nephite|Greek", "", ["Lachon"], "", "~eus", "Greek-looking; cf. Laconia"),
  n("Lamah", "person", "Nephite", "", ["Lam"], "", "~ah", "commander (Morm 6:14)"),
  n("Laman", "person|place", "Lamanite", "", ["Lam"], "", "~an", "also river Laman and a city"),
  n("Lamoni", "person", "Lamanite", "", ["Lam"], "", "~oni"),
  n("Leah", "measure", "Nephite", "", ["Leah"], "", "", "smallest silver measure (Alma 11:17); not the bibl. matriarch"),
  n("Lehi", "person|place", "Nephite|Hebrew", "", ["Leh"], "", "~i", "Heb. lǝḥî 'cheek, jaw' — a place name in Judg 15"),
  n("Lehonti", "person", "Lamanite", "", ["Leh"], "~ont~", "~i"),
  n("Lemuel", "person|place", "Lamanite|Hebrew", "", ["Lemuel"], "", "", "bibl. Lemuel (Prov 31:1); valley of Lemuel"),
  n("Liahona", "object", "Nephite", "", ["Liahona"], "", "", "glossed 'compass' (Alma 37:38); prop. Heb. l-Yāh element — etym. debated"),
  n("Lib", "person", "Jaredite", "", ["Lib"], "", ""),
  n("Limhah", "person", "Nephite", "", ["Lim"], "", "~hah", "commander (Morm 6:14)"),
  n("Limher", "person", "Nephite", "", ["Lim"], "", "~her", "Nephite spy (Alma 2:22)"),
  n("Limhi", "person", "Nephite", "", ["Lim"], "", "~hi"),
  n("Limnah", "measure", "Nephite", "", ["Lim"], "", "~nah", "largest gold measure (Alma 11)"),
  n("Luram", "person", "Nephite", "", ["Lur"], "", "~am", "fallen soldier (Moro 9:2)"),
  n("Mahah", "person", "Jaredite", "", ["Mah"], "", "~ah"),
  n("Mahonri", "person", "Jaredite", "", ["Mah"], "~on~", "~ri", "traditional given name of the brother of Jared (Mahonri Moriancumer); not in the text"),
  n("Manti", "person|place", "Nephite|Egyptian", "", ["Mant"], "", "~i", "prop. cf. Eg. Montu"),
  n("Mathoni", "person", "Nephite|Hebrew", "", ["Math"], "~on~", "~i", "disciple (3 Ne 19:4); cf. Heb. Mattaniah 'gift of Yah'"),
  n("Mathonihah", "person", "Nephite|Hebrew", "", ["Math"], "~on~", "~ihah", "disciple (3 Ne 19:4)"),
  n("Melek", "place", "Nephite|Hebrew", "", ["Melek"], "", "", "Heb. melek 'king'"),
  n("Middoni", "place", "Lamanite", "", ["Midd"], "", "~oni"),
  n("Migron", "place", "Hebrew", "", ["Migr"], "", "~on", "Isaiah quotation (2 Ne 20:28 / Isa 10:28)"),
  n("Minon", "place", "Nephite", "", ["Min"], "", "~on"),
  n("Mocum", "place", "Nephite", "", ["Moc"], "", "~um"),
  n("Moriancumer", "place", "Jaredite", "", ["Mor", "Cum"], "~ian~", "~er", "named for the brother of Jared (Ether 2:13)"),
  n("Morianton", "person|place", "Jaredite|Nephite", "", ["Mor"], "~iant~", "~on", "a Jaredite king and a Nephite land-founder"),
  n("Moriantum", "place", "Nephite", "", ["Mor"], "~iant~", "~um"),
  n("Mormon", "person|place", "Nephite", "", ["Mor"], "", "~mon", "also the waters and forest of Mormon"),
  n("Moron", "person|place", "Jaredite", "", ["Mor"], "", "~on"),
  n("Moroni", "person|place", "Nephite", "", ["Mor"], "~on~", "~i"),
  n("Moronihah", "person|place", "Nephite", "", ["Mor"], "~on~", "~ihah"),
  n("Mosiah", "person", "Nephite|Hebrew", "", ["Mos"], "", "~iah", "prop. Heb. môšîaʿ 'deliverer'"),
  n("Mulek", "person|place", "Mulekite|Hebrew", "", ["Mul"], "", "~ek", "prop. diminutive of melek 'king'; trad. son of Zedekiah"),
  n("Muloki", "person", "Nephite", "", ["Mul"], "", "~oki"),
  n("Nahom", "place", "Hebrew", "", ["Nah"], "", "~om", "burial place (1 Ne 16:34); cf. the NHM tribal region of Yemen; Heb. nḥm 'mourn, comfort'"),
  n("Neas", "plant", "Nephite", "", ["Neas"], "", "", "cultivated plant (Mosiah 9:9)"),
  n("Nehor", "person|place", "Nephite|Hebrew", "", ["Nehor"], "", "", "cf. bibl. Nahor"),
  n("Nephi", "person|place", "Nephite|Egyptian", "", ["Neph"], "", "~i", "prop. Eg. nfr 'good, fair'"),
  n("Nephihah", "person|place", "Nephite", "", ["Neph"], "~i~", "~hah"),
  n("Neum", "person", "Israelite|Hebrew", "", ["Neum"], "", "", "brass-plates prophet; cf. Heb. nǝʾum 'oracle'"),
  n("Nimrah", "person", "Jaredite|Hebrew", "", ["Nimr"], "", "~ah", "cf. bibl. Nimrah (Num 32:3)"),
  n("Ogath", "place", "Jaredite", "", ["Ogath"], "", ""),
  n("Omer", "person", "Jaredite|Hebrew", "", ["Om"], "", "~er", "cf. Heb. ʿōmer (grain measure)"),
  n("Omner", "person|place", "Nephite", "", ["Omn"], "", "~er"),
  n("Omni", "person", "Nephite", "", ["Omn"], "", "~i"),
  n("Onidah", "place", "Nephite|Lamanite", "", ["On"], "", "~idah", "a hill (Alma 32:4) and a place of arms (Alma 47:5)"),
  n("Onihah", "place", "Nephite", "", ["On"], "", "~ihah"),
  n("Onti", "measure", "Nephite", "", ["Ont"], "", "~i", "largest silver measure (Alma 11)"),
  n("Orihah", "person", "Jaredite", "", ["Or"], "", "~ihah", "first Jaredite king"),
  n("Paanchi", "person", "Nephite|Egyptian", "Pa~", ["Anch"], "", "~i", "matches Eg. Paanchi/Piankhi 'the living one'"),
  n("Pachus", "person", "Nephite|Egyptian", "Pa~", ["Chus"], "", "", "king-men leader (Alma 62)"),
  n("Pacumeni", "person", "Nephite|Egyptian", "Pa~", ["Cumen"], "", "~i", "cf. Eg. Pakamen"),
  n("Pagag", "person", "Jaredite", "Pa~", ["Gag"], "", ""),
  n("Pahoran", "person", "Nephite|Egyptian", "Pa~", ["Hor"], "", "~an", "cf. Eg. Pahor 'the Horus'"),
  n("Rabbanah", "title", "Lamanite|Hebrew", "", ["Rabban"], "", "~ah", "glossed 'powerful or great king' (Alma 18:13); cf. Aram. rabbān 'master'"),
  n("Ramah", "place", "Jaredite|Hebrew", "", ["Ram"], "", "~ah", "Jaredite name of the hill Cumorah (Ether 15:11); Heb. rāmāh 'height'"),
  n("Rameumptom", "object", "Nephite|Hebrew", "", ["Ram"], "~eumpt~", "~om", "glossed 'the holy stand' (Alma 31:21); cf. Heb. rām 'high'"),
  n("Riplah", "place", "Nephite", "", ["Ripl"], "", "~ah", "hill Riplah (Alma 43:31)"),
  n("Riplakish", "person", "Jaredite", "", ["Ripl", "Kish"], "~a~", ""),
  n("Ripliancum", "place", "Jaredite", "", ["Ripl", "Cum"], "~ian~", "", "glossed 'large, or to exceed all' (Ether 15:8)"),
  n("Sam", "person", "Nephite|Hebrew", "", ["Sam"], "", "", "prop. short form of Heb. Shem"),
  n("Sariah", "person", "Israelite|Hebrew", "", ["Sar"], "", "~iah", "Heb. Śāryāh 'Yah is prince' — attested at Elephantine"),
  n("Seantum", "person", "Nephite", "Se~", ["Ant"], "", "~um"),
  n("Sebus", "place", "Lamanite", "", ["Seb"], "", "~us", "waters of Sebus (Alma 17:26)"),
  n("Seezoram", "person", "Nephite", "Se~", ["Zoram"], "", "", "murdered chief judge (Hel 9)"),
  n("Senine", "measure", "Nephite", "", ["Sen"], "", "~ine", "gold measure (Alma 11)"),
  n("Senum", "measure", "Nephite", "", ["Sen"], "", "~um", "silver measure (Alma 11)"),
  n("Seon", "measure", "Nephite", "", ["Se"], "", "~on", "gold measure (Alma 11)"),
  n("Shared", "person", "Jaredite", "", ["Shar"], "", "~ed"),
  n("Shazer", "place", "Hebrew", "", ["Shaz"], "", "~er", "camp site (1 Ne 16:13); prop. Semitic 'trees'"),
  n("Shelem", "place", "Jaredite|Hebrew", "", ["Shel"], "", "~em", "mount Shelem (Ether 3:1); cf. Heb. šlm 'whole, peace'"),
  n("Shemlon", "place", "Lamanite", "", ["Shem"], "", "~lon"),
  n("Shemnon", "person", "Nephite", "", ["Shem"], "", "~non", "disciple (3 Ne 19:4)"),
  n("Sherem", "person", "Nephite", "", ["Sher"], "", "~em"),
  n("Sherrizah", "place", "Nephite", "", ["Sherr"], "~iz~", "~ah", "tower of Sherrizah (Moro 9:7)"),
  n("Sheum", "plant", "Nephite|Akkadian", "", ["Sheum"], "", "", "grain (Mosiah 9:9); matches Akkadian še'um 'barley'"),
  n("Shez", "person", "Jaredite", "", ["Shez"], "", ""),
  n("Shiblom", "person", "Jaredite|Nephite", "", ["Shibl"], "", "~om", "a Jaredite king and a Nephite commander (Morm 6:14)"),
  n("Shiblon", "person|measure", "Nephite", "", ["Shibl"], "", "~on", "son of Alma; also a silver measure (Alma 11)"),
  n("Shiblum", "measure", "Nephite", "", ["Shibl"], "", "~um", "silver measure (Alma 11:16); 1830 ed. reads 'shilum'"),
  n("Shilom", "place", "Nephite|Hebrew", "", ["Shil"], "", "~om", "cf. Heb. Shiloh / šālôm"),
  n("Shim", "place", "Nephite", "", ["Shim"], "", "", "hill Shim (Morm 1:3)"),
  n("Shimnilom", "place", "Lamanite", "", ["Shim"], "~nil~", "~om", "city of Lamanite converts (Alma 23:12)"),
  n("Shiz", "person", "Jaredite", "", ["Shiz"], "", ""),
  n("Shule", "person", "Jaredite", "", ["Shule"], "", ""),
  n("Shum", "measure", "Nephite", "", ["Shum"], "", "", "gold measure (Alma 11)"),
  n("Sidom", "place", "Nephite", "", ["Sid"], "", "~om"),
  n("Sidon", "place", "Nephite|Hebrew", "", ["Sid"], "", "~on", "river Sidon; cf. Phoenician Sidon"),
  n("Siron", "place", "Lamanite", "", ["Sir"], "", "~on", "borders of the Lamanites (Alma 39:3)"),
  n("Teancum", "person|place", "Nephite", "", ["Tean", "Cum"], "", ""),
  n("Teomner", "person", "Nephite", "", ["Teom"], "", "~ner", "prop. Heb. tǝʾōm 'twin'"),
  n("Tubaloth", "person", "Lamanite|Hebrew", "", ["Tubal"], "", "~oth", "cf. bibl. Tubal"),
  n("Zarahemla", "person|place", "Mulekite|Hebrew", "", ["Zara", "Heml"], "", "~a", "prop. Heb. zeraʿ-ḥemlāh 'seed of compassion'"),
  n("Zeezrom", "person|place", "Nephite", "Ze~", ["Ez"], "~r~", "~om", "also a city (3 Ne 9:8); poss. 'he of the ezrom (silver)'"),
  n("Zemnarihah", "person", "Nephite", "", ["Zem"], "~nar~", "~ihah", "hanged robber chief (3 Ne 4:28)"),
  n("Zenephi", "person", "Nephite", "Ze~", ["Neph"], "", "~i"),
  n("Zeniff", "person", "Nephite", "Ze~", ["Niff"], "", "", "prop. Ze~ + Nephi element"),
  n("Zenock", "person", "Israelite", "Ze~", ["Nock"], "", "", "brass-plates prophet; prop. Ze~ + Enoch"),
  n("Zenos", "person", "Israelite", "Ze~", ["Nos"], "", "", "brass-plates prophet; prop. Ze~ + Enosh"),
  n("Zeram", "person", "Nephite", "", ["Zer"], "", "~am", "Nephite spy (Alma 2:22)"),
  n("Zerahemnah", "person", "Lamanite", "", ["Zera", "Hemn"], "", "~ah", "Zoramite-led Lamanite commander; poss. var. of Zarahemla"),
  n("Zerin", "place", "Jaredite", "", ["Zer"], "", "~in", "mount Zerin (Ether 12:30)"),
  n("Ziff", "material", "Nephite", "", ["Ziff"], "", "", "unknown metal (Mosiah 11:3); cf. Heb. zîw 'brightness'"),
  n("Zoram", "person", "Nephite|Hebrew", "", ["Zor"], "", "~am", "Laban's servant; etym. debated (prop. ṣūr 'rock' + ʿam)"),
];

// Facet inventories derived from the data, for the filter UI.
const uniq = (arr) => [...new Set(arr)].sort();
export const facets = {
  prefixes: uniq(names.map((x) => x.prefix).filter(Boolean)),
  stems: uniq(names.flatMap((x) => x.stems)),
  affixes: uniq(names.map((x) => x.affix).filter(Boolean)),
  suffixes: uniq(names.map((x) => x.suffix).filter(Boolean)),
  cultures: uniq(names.flatMap((x) => x.cultures)),
  types: uniq(names.flatMap((x) => x.types)),
};

export default names.sort((a, b) => a.name.localeCompare(b.name));
