/**
 * Bot scheduler — proactive bot posting (the cron). A 60s tick selects due
 * bom_bot_schedule rows and runs their action; new_prompt posts an unposted
 * discussion prompt to the channel as a tagged bot, then has the channel's bots
 * comment (each reply generated by its Mastra agent). Multi-instance safe via a
 * Redis lock; single-node falls through.
 */
import type { Kysely } from 'kysely';
import { sql } from 'kysely';
import type { DB } from '../../codegen/db.js';
import { getDb } from '../data/db.js';
import { getRedis } from '../config/redis.js';
import { getBus } from '../realtime/RealtimeBus.js';
import { postMessage, getThread } from '../messaging/messages.js';
import { generateBotReply, type BotTurn } from './generate.js';

const TICK_MS = 60_000;
let timer: ReturnType<typeof setInterval> | null = null;
let ticking = false;

interface BotChannelConfig {
  tag?: string;
  comment_min?: number;
  comment_max?: number;
  prompt_thread?: { role: string; content: string }[];
  enabled?: boolean;
}

function parseBotConfig(metadata: unknown): BotChannelConfig | null {
  if (metadata == null) return null;
  let obj: Record<string, unknown>;
  try { obj = typeof metadata === 'string' ? JSON.parse(metadata) : (metadata as Record<string, unknown>); } catch { return null; }
  const bot = obj?.['bot'];
  return bot && typeof bot === 'object' ? (bot as BotChannelConfig) : null;
}

const rand = (n: number) => Math.floor(Math.random() * n);
const randInt = (min: number, max: number) => min + rand(Math.max(0, max - min) + 1);

function fillPlaceholders(s: string, prompt: { reference: string | null; prompt: string | null }): string {
  return s
    .replace('[[scripture]]', prompt.reference ?? '')
    .replace('[[question]]', prompt.prompt ?? '')
    .replace(/\[\[(context|synopsis|crossreferences)\]\]/g, '(not available)');
}

/**
 * Post one discussion round to a bot channel: a bot opens with a prompt, then
 * the channel's bots comment. Exported so it can be triggered directly (tests,
 * admin) as well as by the scheduler. Returns a small summary.
 */
export async function runNewPrompt(db: Kysely<DB>, channelUrl: string): Promise<{ posted: number; reason?: string; promptGuid?: string }> {
  const ch = await db.selectFrom('messenger_channels').select(['metadata', 'lang']).where('channel_url', '=', channelUrl).executeTakeFirst();
  if (!ch) return { posted: 0, reason: 'no-channel' };
  const cfg = parseBotConfig(ch.metadata);
  if (!cfg || !cfg.enabled || !cfg.tag) return { posted: 0, reason: 'no-bot-config' };
  const lang = ch.lang ?? 'en';

  const prompt = await db
    .selectFrom('bom_virtualgroup_prompts')
    .select(['guid', 'reference', 'prompt'])
    .where('group_id', '=', cfg.tag)
    .where('lang', '=', lang)
    .where('thread_id', 'is', null)
    .orderBy(sql`RAND()`)
    .limit(1)
    .executeTakeFirst();
  if (!prompt) return { posted: 0, reason: 'no-unposted-prompts' };

  const bots = await db
    .selectFrom('bom_bot')
    .select(['bot_id', 'display_name'])
    .where('enabled', '=', 1)
    .where('bot_class', '=', 'community')
    .where(sql<boolean>`JSON_CONTAINS(tags, ${JSON.stringify(cfg.tag)})`)
    .execute();
  if (!bots.length) return { posted: 0, reason: 'no-bots' };

  // 1. a bot opens with the prompt
  const opener = bots[rand(bots.length)]!;
  const promptText = `${prompt.reference ? prompt.reference + ' — ' : ''}${prompt.prompt ?? ''}`.trim();
  const openMsg = await postMessage(db, { channelUrl, userId: opener.bot_id, message: promptText, customType: 'bot_prompt' });
  getBus().emit('message_received', channelUrl, openMsg);
  await db.updateTable('bom_virtualgroup_prompts').set({ thread_id: openMsg.message_id }).where('guid', '=', prompt.guid).execute();

  // 2. the channel's bots comment (each via its Mastra agent)
  const n = randInt(cfg.comment_min ?? 1, cfg.comment_max ?? 3);
  let last = opener.bot_id;
  let posted = 1;
  for (let i = 0; i < n; i++) {
    const pool = bots.filter((b) => b.bot_id !== last);
    const speaker = (pool.length ? pool : bots)[rand(pool.length || bots.length)]!;
    const thread = await getThread(db, openMsg.message_id);
    const priming: BotTurn[] = (cfg.prompt_thread ?? []).map((m) => ({
      role: m.role === 'assistant' ? 'assistant' : 'user',
      content: fillPlaceholders(m.content, prompt),
    }));
    const convo: BotTurn[] = [
      { role: 'user', content: promptText },
      ...thread.map((t) => ({ role: (t.user?.user_id === speaker.bot_id ? 'assistant' : 'user') as 'assistant' | 'user', content: t.message })),
    ];
    const reply = await generateBotReply(db, speaker.bot_id, [...priming, ...convo]);
    if (!reply) continue;
    const cmt = await postMessage(db, { channelUrl, userId: speaker.bot_id, message: reply, parentMessageId: openMsg.message_id, customType: 'bot_comment' });
    getBus().emit('message_received', channelUrl, cmt);
    last = speaker.bot_id;
    posted++;
  }
  return { posted, promptGuid: prompt.guid };
}

async function tick(): Promise<void> {
  if (ticking) return;
  ticking = true;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let redis: any = null;
  try {
    redis = getRedis();
    if (redis) {
      const ok = await redis.set('bots:scheduler:lock', '1', { NX: true, EX: 50 });
      if (!ok) return; // another instance owns this tick
    }
    const db = getDb();
    const now = new Date();
    const due = await db
      .selectFrom('bom_bot_schedule')
      .selectAll()
      .where('enabled', '=', 1)
      .where((eb) => eb.or([eb('next_run_at', 'is', null), eb('next_run_at', '<=', now)]))
      .execute();
    for (const row of due) {
      try {
        if (row.action === 'new_prompt') await runNewPrompt(db, row.channel_url);
      } catch (e) {
        console.error('[bots] schedule', row.id, 'failed:', (e as Error).message);
      }
      const minutes = row.cadence_minutes ?? 1440;
      await db
        .updateTable('bom_bot_schedule')
        .set({ last_run_at: now, next_run_at: new Date(Date.now() + minutes * 60_000) })
        .where('id', '=', row.id)
        .execute();
    }
  } catch (e) {
    console.error('[bots] scheduler tick error:', (e as Error).message);
  } finally {
    ticking = false;
    if (redis) { try { await redis.del('bots:scheduler:lock'); } catch { /* ignore */ } }
  }
}

export function startBotScheduler(): void {
  if (timer) return;
  timer = setInterval(() => { void tick(); }, TICK_MS);
  if (typeof timer.unref === 'function') timer.unref();
  console.info('[bots] scheduler started (60s tick)');
}

export function stopBotScheduler(): void {
  if (timer) { clearInterval(timer); timer = null; }
}
