export type GeometryRow = {
  uid: number;
  version: string;
  verseId: number;
  page: number;
  imagePage: number;
  pageWidth: number;
  pageScale: number;
  X: number;
  Y: number;
  W: number;
  H: number;
  TLW: number;
  TLH: number;
  BRW: number;
  BRH: number;
};

export type Severity = 'error' | 'warning' | 'info';
export type Tier = 'deterministic' | 'forced' | 'statistical' | 'coverage';

export type AuditFinding = {
  code: string;
  severity: Severity;
  tier: Tier;
  confidence: number;
  version: string;
  uid?: number;
  verseId?: number;
  page?: number;
  imagePage?: number;
  message: string;
  evidence?: Record<string, unknown>;
  peers?: Array<Pick<GeometryRow, 'uid' | 'version' | 'verseId' | 'page' | 'imagePage'>>;
  proposedGeometry?: Partial<Pick<GeometryRow, 'X' | 'Y' | 'W' | 'H' | 'TLW' | 'TLH' | 'BRW' | 'BRH'>> | null;
  autoRepairEligible: boolean;
};

export type EditionMeta = {
  version: string;
  pages: number | null;
  pgfirstVerse: number;
  format: string;
  imageOffset: number;
};

export type FamilyDefinition = {
  id: string;
  members: string[];
  reference?: string;
};

export type PagePlacement = {
  row: GeometryRow;
  column: number;
  columnCount: number;
  columnLeft: number;
  columnRight: number;
  columnTop: number;
  columnBottom: number;
};

export const DEFAULT_FAMILIES: FamilyDefinition[] = [
  {
    id: 'european-1852-plates',
    members: ['1852', '1854', '1854l', '1866', '1871', '1874', '1877'],
    reference: '1852',
  },
  {
    // `printer` is a derived presentation of the 1829 setting. Keeping this
    // relationship explicit lets the audit detect divergence without assuming
    // every visually similar edition is a plate mate.
    id: '1829-printer-derivative',
    members: ['1829', 'printer'],
    reference: '1829',
  },
  {
    // These versions were generated by explicit 1879 -> target
    // re-registration jobs. Other visually similar editions are intentionally
    // absent because the retained family scanner classifies them as distinct.
    id: '1879-reregistered-derivatives',
    members: ['1879', '1881', '1883d', '1885', '1888d', '1898', '1907', '1918'],
    reference: '1879',
  },
  {
    // The retained generation driver explicitly uses 1920 as the seed for
    // both derivative geometries.
    id: '1920-reregistered-derivatives',
    members: ['1920', '1921', '1923'],
    reference: '1920',
  },
];

const geometryFields = ['X', 'Y', 'W', 'H', 'TLW', 'TLH', 'BRW', 'BRH'] as const;

function finding(
  row: GeometryRow,
  code: string,
  severity: Severity,
  tier: Tier,
  message: string,
  evidence?: Record<string, unknown>,
  proposedGeometry: AuditFinding['proposedGeometry'] = null,
  autoRepairEligible = false,
): AuditFinding {
  return {
    code,
    severity,
    tier,
    confidence: tier === 'deterministic' ? 1 : tier === 'forced' ? 0.98 : 0.8,
    version: row.version,
    uid: row.uid,
    verseId: row.verseId,
    page: row.page,
    imagePage: row.imagePage,
    message,
    evidence,
    proposedGeometry,
    autoRepairEligible,
  };
}

export function median(values: number[]): number {
  if (!values.length) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
}

export function percentile(values: number[], p: number): number {
  if (!values.length) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.max(0, Math.min(sorted.length - 1, Math.round((sorted.length - 1) * p)));
  return sorted[index]!;
}

export function mad(values: number[], center = median(values)): number {
  return median(values.map((value) => Math.abs(value - center)));
}

export function robustZ(value: number, values: number[]): number {
  if (values.length < 5) return 0;
  const center = median(values);
  const spread = mad(values, center);
  if (spread === 0) return value === center ? 0 : Number.POSITIVE_INFINITY;
  return Math.abs(value - center) / (1.4826 * spread);
}

export function robustDistanceSummary(values: number[]): {
  count: number;
  median: number;
  mad: number;
  p95: number;
  p99: number;
  max: number;
} {
  const center = median(values);
  return {
    count: values.length,
    median: center,
    mad: mad(values, center),
    p95: percentile(values, 0.95),
    p99: percentile(values, 0.99),
    max: values.length ? Math.max(...values) : 0,
  };
}

export function robustDistanceOutlier(
  value: number,
  population: number[],
  zThreshold = 7,
  classicZThreshold = 3,
): { outlier: boolean; robustZ: number | null; classicZ: number | null; percentile: number } {
  const summary = robustDistanceSummary(population);
  const z = summary.mad > 0
    ? Math.abs(value - summary.median) / (1.4826 * summary.mad)
    : value === summary.median ? 0 : null;
  const average = population.reduce((sum, candidate) => sum + candidate, 0) /
    Math.max(1, population.length);
  const standardDeviation = Math.sqrt(population.reduce((sum, candidate) =>
    sum + (candidate - average) ** 2, 0) / Math.max(1, population.length));
  const classicZ = standardDeviation > 0 ? Math.abs(value - average) / standardDeviation : null;
  const rank = population.filter((candidate) => candidate <= value).length / Math.max(1, population.length);
  return {
    outlier: population.length >= 20 &&
      value >= Math.max(3, summary.p99) &&
      (z == null
        ? classicZ != null && classicZ >= classicZThreshold
        : z >= zThreshold),
    robustZ: z,
    classicZ,
    percentile: rank,
  };
}

export function notchActive(width: number, height: number): boolean {
  // Historical rows sometimes use width=1,height=0 as a no-notch sentinel.
  return width > 1 && height > 0;
}

export function effectiveArea(row: GeometryRow): number {
  // The two corner cutouts can overlap when integer-rounded line bands touch.
  // Subtract their union, not both areas independently.
  const overlapWidth = Math.max(0, row.TLW + row.BRW - row.W);
  const overlapHeight = Math.max(0, row.TLH + row.BRH - row.H);
  const notchOverlap = overlapWidth * overlapHeight;
  return row.W * row.H - row.TLW * row.TLH - row.BRW * row.BRH + notchOverlap;
}

export function geometryVector(row: GeometryRow): number[] {
  return geometryFields.map((field) => row[field]);
}

export function exactGeometryKey(row: GeometryRow): string {
  return `${row.page}|${geometryVector(row).join('|')}`;
}

export function rectIou(a: GeometryRow, b: GeometryRow): number {
  const left = Math.max(a.X, b.X);
  const top = Math.max(a.Y, b.Y);
  const right = Math.min(a.X + a.W, b.X + b.W);
  const bottom = Math.min(a.Y + a.H, b.Y + b.H);
  const intersection = Math.max(0, right - left) * Math.max(0, bottom - top);
  if (!intersection) return 0;
  return intersection / (a.W * a.H + b.W * b.H - intersection);
}

export function auditAbsoluteGeometry(
  rows: GeometryRow[],
  metas: Map<string, EditionMeta>,
): AuditFinding[] {
  const findings: AuditFinding[] = [];
  for (const row of rows) {
    const badFields = geometryFields.filter((field) => !Number.isFinite(row[field]) || !Number.isInteger(row[field]));
    if (badFields.length) {
      findings.push(finding(row, 'NON_INTEGER_GEOMETRY', 'error', 'deterministic',
        `Non-finite or non-integer geometry: ${badFields.join(', ')}`, { fields: badFields }));
      continue;
    }
    if (!Number.isInteger(row.page) || row.page <= 0) {
      findings.push(finding(row, 'INVALID_STORED_PAGE', 'error', 'deterministic',
        `Stored page must be a positive integer; got ${row.page}`, { storedPage: row.page }));
    }
    if (row.pageScale <= 0 || row.pageWidth <= 0) {
      findings.push(finding(row, 'INVALID_PAGE_SCALE', 'error', 'deterministic',
        'pageScale and pageWidth must both be positive', { pageScale: row.pageScale, pageWidth: row.pageWidth }));
    }
    if (row.W <= 0 || row.H <= 0) {
      findings.push(finding(row, 'NON_POSITIVE_SIZE', 'error', 'deterministic',
        `Box has non-positive size ${row.W}×${row.H}`, { W: row.W, H: row.H }));
    }
    if (row.X < 0 || row.Y < 0) {
      findings.push(finding(row, 'NEGATIVE_ORIGIN', row.X < -2 || row.Y < -2 ? 'error' : 'warning',
        'deterministic', `Box origin is negative (${row.X},${row.Y})`, { X: row.X, Y: row.Y }));
    }
    if (row.pageScale > 0 && (row.X >= row.pageScale || row.X + row.W > row.pageScale + 2)) {
      const overflow = row.X + row.W - row.pageScale;
      const severe = row.X >= row.pageScale || overflow > row.pageScale * 0.1;
      findings.push(finding(row, 'HORIZONTAL_BOUNDS', severe ? 'error' : 'warning',
        severe ? 'deterministic' : 'statistical',
        severe
          ? 'Box lies outside the normalized page frame'
          : 'Box modestly exceeds the nominal pageScale frame; this may be intentional scan bleed',
        { X: row.X, W: row.W, right: row.X + row.W, pageScale: row.pageScale, overflow }));
    }
    const meta = metas.get(row.version);
    if (row.imagePage <= 0 || (meta?.pages && row.imagePage > meta.pages)) {
      findings.push(finding(row, 'INDEX_OUTSIDE_SCAN_RANGE', 'error', 'deterministic',
        `Resolved image page ${row.imagePage} is outside the edition scan range`,
        { storedPage: row.page, imagePage: row.imagePage, editionPages: meta?.pages ?? null }));
    }

    for (const [prefix, width, height] of [
      ['TL', row.TLW, row.TLH],
      ['BR', row.BRW, row.BRH],
    ] as const) {
      if (width < 0 || width > row.W) {
        findings.push(finding(row, `INVALID_${prefix}_NOTCH_WIDTH`, 'error', 'deterministic',
          `${prefix} notch width ${width} is outside [0,${row.W}]`, { width, W: row.W }));
      }
      if (height < 0 || height > row.H) {
        findings.push(finding(row, `INVALID_${prefix}_NOTCH_HEIGHT`, 'error', 'deterministic',
          `${prefix} notch height ${height} is outside [0,${row.H}]`, { height, H: row.H }));
      }
      const sentinel = width <= 1 && height === 0;
      if (!sentinel && ((width > 1 && height === 0) || (width <= 1 && height > 0))) {
        findings.push(finding(row, `HALF_${prefix}_NOTCH`, 'warning', 'deterministic',
          `${prefix} notch has only one active dimension and therefore does not affect the rendered polygon`,
          { width, height },
          prefix === 'TL' ? { TLW: 0, TLH: 0 } : { BRW: 0, BRH: 0 }));
      }
    }

    const area = effectiveArea(row);
    if (area <= 0) {
      findings.push(finding(row, 'EMPTY_POLYGON', 'error', 'deterministic',
        `Notches remove the complete outer rectangle (effective area ${area})`,
        { outerArea: row.W * row.H, effectiveArea: area }));
    } else if (row.W > 0 && row.H > 0 && area / (row.W * row.H) < 0.12) {
      findings.push(finding(row, 'TINY_EFFECTIVE_AREA', 'warning', 'statistical',
        'Less than 12% of the outer rectangle remains included',
        { outerArea: row.W * row.H, effectiveArea: area, ratio: area / (row.W * row.H) }));
    }

    const verticalNotchOverlap = row.TLH + row.BRH - row.H;
    const roundingTolerance = Math.max(3, Math.round(Math.min(row.TLH, row.BRH) * 0.12));
    if (notchActive(row.TLW, row.TLH) && notchActive(row.BRW, row.BRH) &&
        verticalNotchOverlap > roundingTolerance && row.TLW + row.BRW >= row.W) {
      findings.push(finding(row, 'DISCONNECTED_POLYGON', 'error', 'deterministic',
        'Overlapping opposing notches remove every horizontal connection',
        {
          TLW: row.TLW,
          TLH: row.TLH,
          BRW: row.BRW,
          BRH: row.BRH,
          W: row.W,
          H: row.H,
          verticalNotchOverlap,
          roundingTolerance,
        }));
    }
  }
  return findings;
}

type ColumnModel = {
  index: number;
  rows: GeometryRow[];
  left: number;
  right: number;
  top: number;
  bottom: number;
};

function splitColumns(pageRows: GeometryRow[]): ColumnModel[] {
  if (!pageRows.length) return [];
  if (pageRows.length < 4) {
    return [{
      index: 0,
      rows: [...pageRows],
      left: median(pageRows.map((row) => row.X)),
      right: median(pageRows.map((row) => row.X + row.W)),
      top: Math.min(...pageRows.map((row) => row.Y)),
      bottom: Math.max(...pageRows.map((row) => row.Y + row.H)),
    }];
  }
  const centers = pageRows
    .map((row) => ({ row, center: row.X + row.W / 2 }))
    .sort((a, b) => a.center - b.center);
  let splitAt = -1;
  let largestGap = 0;
  for (let i = 1; i < centers.length; i++) {
    const gap = centers[i]!.center - centers[i - 1]!.center;
    if (gap > largestGap) {
      largestGap = gap;
      splitAt = i;
    }
  }
  const typicalWidth = median(pageRows.map((row) => row.W));
  const groups = splitAt >= 2 && centers.length - splitAt >= 2 && largestGap > Math.max(25, typicalWidth * 0.45)
    ? [centers.slice(0, splitAt).map((item) => item.row), centers.slice(splitAt).map((item) => item.row)]
    : [centers.map((item) => item.row)];
  return groups.map((group, index) => ({
    index,
    rows: group,
    left: median(group.map((row) => row.X)),
    right: median(group.map((row) => row.X + row.W)),
    top: Math.min(...group.map((row) => row.Y)),
    bottom: Math.max(...group.map((row) => row.Y + row.H)),
  }));
}

export function buildPagePlacements(rows: GeometryRow[]): Map<number, PagePlacement> {
  const out = new Map<number, PagePlacement>();
  const byVersionPage = new Map<string, GeometryRow[]>();
  for (const row of rows) {
    const key = `${row.version}|${row.imagePage}`;
    (byVersionPage.get(key) ?? byVersionPage.set(key, []).get(key)!).push(row);
  }
  for (const pageRows of byVersionPage.values()) {
    const columns = splitColumns(pageRows);
    for (const column of columns) {
      for (const row of column.rows) {
        out.set(row.uid, {
          row,
          column: column.index,
          columnCount: columns.length,
          columnLeft: column.left,
          columnRight: column.right,
          columnTop: column.top,
          columnBottom: column.bottom,
        });
      }
    }
  }
  return out;
}

function readingOrder(a: PagePlacement, b: PagePlacement): number {
  return a.row.imagePage - b.row.imagePage ||
    a.column - b.column ||
    a.row.Y - b.row.Y ||
    a.row.X - b.row.X ||
    a.row.verseId - b.row.verseId;
}

function samePrintedLine(a: GeometryRow, b: GeometryRow): boolean {
  const aTop = a.Y + a.H - (notchActive(a.BRW, a.BRH) ? a.BRH : Math.min(a.H, 24));
  const aBottom = a.Y + a.H;
  const bTop = b.Y;
  const bBottom = b.Y + (notchActive(b.TLW, b.TLH) ? b.TLH : Math.min(b.H, 24));
  const overlap = Math.max(0, Math.min(aBottom, bBottom) - Math.max(aTop, bTop));
  return overlap >= Math.min(4, Math.max(1, Math.min(aBottom - aTop, bBottom - bTop) * 0.25));
}

function isImmediateBreak(a: PagePlacement, b: PagePlacement): boolean {
  if (a.row.imagePage === b.row.imagePage) {
    return b.column === a.column + 1;
  }
  return b.row.imagePage === a.row.imagePage + 1 &&
    a.column === a.columnCount - 1 &&
    b.column === 0;
}

export function auditOrderingAndNotches(rows: GeometryRow[]): AuditFinding[] {
  const findings: AuditFinding[] = [];
  const placements = buildPagePlacements(rows);
  const byVersion = new Map<string, PagePlacement[]>();
  for (const placement of placements.values()) {
    (byVersion.get(placement.row.version) ?? byVersion.set(placement.row.version, []).get(placement.row.version)!)
      .push(placement);
  }

  for (const editionRows of byVersion.values()) {
    editionRows.sort(readingOrder);
    const orderIndex = new Map(editionRows.map((placement, index) => [placement.row.uid, index]));
    for (let i = 1; i < editionRows.length; i++) {
      const previous = editionRows[i - 1]!;
      const current = editionRows[i]!;
      if (current.row.verseId < previous.row.verseId && current.row.verseId !== previous.row.verseId) {
        findings.push(finding(current.row, 'VERSE_ORDER_INVERSION', 'error', 'deterministic',
          `Reading order falls from verse ${previous.row.verseId} to ${current.row.verseId}`,
          { previousUid: previous.row.uid, previousVerseId: previous.row.verseId }));
      }
    }

    const byVerse = new Map<number, PagePlacement[]>();
    for (const placement of editionRows) {
      (byVerse.get(placement.row.verseId) ?? byVerse.set(placement.row.verseId, []).get(placement.row.verseId)!)
        .push(placement);
    }
    for (const fragments of byVerse.values()) {
      fragments.sort(readingOrder);
      for (let i = 1; i < fragments.length; i++) {
        const previous = fragments[i - 1]!;
        const current = fragments[i]!;
        if (current.row.imagePage - previous.row.imagePage > 1) {
          findings.push(finding(current.row, 'PAGE_JUMP_WITHIN_VERSE', 'warning', 'coverage',
            `Verse continuation jumps from image page ${previous.row.imagePage} to ${current.row.imagePage}`,
            { previousUid: previous.row.uid, previousImagePage: previous.row.imagePage }));
        }
        const previousIndex = orderIndex.get(previous.row.uid)!;
        const currentIndex = orderIndex.get(current.row.uid)!;
        const intervening = editionRows
          .slice(previousIndex + 1, currentIndex)
          .filter((placement) => placement.row.verseId !== previous.row.verseId);
        if (intervening.length) {
          findings.push(finding(current.row, 'INTERLEAVED_VERSE_FRAGMENT', 'error', 'deterministic',
            `Verse ${current.row.verseId} reappears after later verse geometry`,
            {
              previousUid: previous.row.uid,
              intervening: intervening.slice(0, 8).map((placement) => ({
                uid: placement.row.uid,
                verseId: placement.row.verseId,
                imagePage: placement.row.imagePage,
              })),
            }));
          continue;
        }
        if (!isImmediateBreak(previous, current)) continue;
        if (notchActive(previous.row.BRW, previous.row.BRH)) {
          findings.push(finding(previous.row,
            previous.row.imagePage === current.row.imagePage
              ? 'BR_NOTCH_AT_COLUMN_CONTINUATION'
              : 'BR_NOTCH_AT_PAGE_CONTINUATION',
            'warning', 'statistical',
            'A continuing verse has a bottom-right notch at a column/page break; pixel/OCR evidence must determine whether it is a valid trailing-word boundary',
            { continuationUid: current.row.uid, continuationImagePage: current.row.imagePage }));
        }
        if (notchActive(current.row.TLW, current.row.TLH)) {
          findings.push(finding(current.row,
            previous.row.imagePage === current.row.imagePage
              ? 'TL_NOTCH_AT_COLUMN_CONTINUATION'
              : 'TL_NOTCH_AT_PAGE_CONTINUATION',
            'warning', 'statistical',
            'A continuing verse has a top-left notch after a column/page break; pixel/OCR evidence must determine whether it is valid',
            { previousUid: previous.row.uid, previousImagePage: previous.row.imagePage }));
        }
      }
    }

    const byLocation = new Map<string, PagePlacement[]>();
    const allPairedGaps: Array<{ row: GeometryRow; next: GeometryRow; gap: number }> = [];
    for (const placement of editionRows) {
      const key = `${placement.row.imagePage}|${placement.column}`;
      (byLocation.get(key) ?? byLocation.set(key, []).get(key)!).push(placement);
    }
    for (const locationRows of byLocation.values()) {
      locationRows.sort((a, b) => a.row.Y - b.row.Y || a.row.X - b.row.X || a.row.verseId - b.row.verseId);
      for (const rowPlacement of locationRows) {
        const row = rowPlacement.row;
        if (notchActive(row.BRW, row.BRH)) {
          const next = locationRows.find((candidate) =>
            candidate.row.verseId === row.verseId + 1 &&
            samePrintedLine(row, candidate.row));
          if (!next) {
            findings.push(finding(row, 'ORPHAN_BR_NOTCH', 'warning', 'statistical',
              'Bottom-right notch has no following canonical verse on the same inferred line'));
          } else {
            const a = row.X + row.W - row.BRW;
            const b = next.row.X + next.row.TLW;
            if (!notchActive(next.row.TLW, next.row.TLH)) {
              findings.push(finding(row, 'NONRECIPROCAL_NOTCH_PAIR', 'warning', 'statistical',
                'Bottom-right notch is not complemented by the following verse',
                { followingUid: next.row.uid, currentBoundary: a }));
            } else {
              allPairedGaps.push({ row, next: next.row, gap: b - a });
            }
          }
        }
        if (notchActive(row.TLW, row.TLH)) {
          const previous = locationRows.find((candidate) =>
            candidate.row.verseId === row.verseId - 1 &&
            samePrintedLine(candidate.row, row));
          if (!previous) {
            findings.push(finding(row, 'ORPHAN_TL_NOTCH', 'warning', 'statistical',
              'Top-left notch has no preceding canonical verse on the same inferred line'));
          }
        }
      }
    }
    const gaps = allPairedGaps.map((pair) => pair.gap);
    const gapMedian = median(gaps);
    const gapMad = mad(gaps, gapMedian);
    for (const pair of allPairedGaps) {
      const z = gaps.length >= 20 && gapMad > 0
        ? Math.abs(pair.gap - gapMedian) / (1.4826 * gapMad)
        : 0;
      if (z >= 7) {
        findings.push(finding(pair.row, 'NOTCH_PAIR_GAP_OUTLIER', 'warning', 'statistical',
          'Spacing between adjacent verse notch boundaries is a robust edition-level outlier',
          {
            followingUid: pair.next.uid,
            gap: pair.gap,
            medianGap: gapMedian,
            gapMad,
            robustZ: Number(z.toFixed(3)),
            currentBoundary: pair.row.X + pair.row.W - pair.row.BRW,
            followingBoundary: pair.next.X + pair.next.TLW,
          }));
      }
    }
  }
  return findings;
}

export function auditDuplicatesAndOverlaps(rows: GeometryRow[]): AuditFinding[] {
  const findings: AuditFinding[] = [];
  const byVersionPage = new Map<string, GeometryRow[]>();
  for (const row of rows) {
    const key = `${row.version}|${row.imagePage}`;
    (byVersionPage.get(key) ?? byVersionPage.set(key, []).get(key)!).push(row);
  }
  for (const pageRows of byVersionPage.values()) {
    for (let i = 0; i < pageRows.length; i++) {
      const a = pageRows[i]!;
      for (let j = i + 1; j < pageRows.length; j++) {
        const b = pageRows[j]!;
        if (a.verseId === b.verseId && exactGeometryKey(a) === exactGeometryKey(b)) {
          findings.push(finding(b, 'EXACT_DUPLICATE_FRAGMENT', 'error', 'deterministic',
            'The same verse has two identical geometry rows',
            { duplicateUid: a.uid }, null, true));
          continue;
        }
        if (a.verseId === b.verseId) continue;
        const iou = rectIou(a, b);
        if (iou >= 0.9) {
          const exact = geometryVector(a).every((value, index) => value === geometryVector(b)[index]);
          const target = a.verseId < b.verseId ? a : b;
          const peer = target === a ? b : a;
          findings.push({
            ...finding(target, exact ? 'DIFFERENT_VERSE_EXACT_GEOMETRY' : 'DIFFERENT_VERSE_NEAR_DUPLICATE',
              'error', exact ? 'deterministic' : 'statistical',
              `Different verses claim ${Math.round(iou * 100)}% overlapping outer rectangles`,
              { peerUid: peer.uid, peerVerseId: peer.verseId, rectangleIou: Number(iou.toFixed(4)) }),
            peers: [peer],
          });
        }
      }
    }
  }
  return findings;
}

export function auditCoverage(
  rows: GeometryRow[],
  versions: string[],
  canonicalMin = 31103,
  canonicalMax = 37706,
): AuditFinding[] {
  const findings: AuditFinding[] = [];
  for (const version of versions) {
    const editionRows = rows.filter((row) => row.version === version);
    if (!editionRows.length) {
      findings.push({
        code: 'MISSING_VERSION',
        severity: 'error',
        tier: 'coverage',
        confidence: 1,
        version,
        message: 'Edition has no rows in bom_xtras_fax_index',
        autoRepairEligible: false,
      });
      continue;
    }
    const present = new Set(editionRows.map((row) => row.verseId));
    let runStart: number | null = null;
    for (let verseId = canonicalMin; verseId <= canonicalMax + 1; verseId++) {
      if (verseId <= canonicalMax && !present.has(verseId)) {
        runStart ??= verseId;
      } else if (runStart != null) {
        const end = verseId - 1;
        const length = end - runStart + 1;
        findings.push({
          code: length === 1 ? 'MISSING_VERSE' : 'MISSING_VERSE_RUN',
          severity: length >= 10 ? 'error' : 'warning',
          tier: 'coverage',
          confidence: 1,
          version,
          verseId: runStart,
          message: `Missing canonical verse${length === 1 ? '' : ' run'} ${runStart}${length === 1 ? '' : `–${end}`}`,
          evidence: { startVerseId: runStart, endVerseId: end, length },
          autoRepairEligible: false,
        });
        runStart = null;
      }
    }
    const pages = [...new Set(editionRows.map((row) => row.imagePage))].sort((a, b) => a - b);
    for (let i = 1; i < pages.length; i++) {
      const gap = pages[i]! - pages[i - 1]! - 1;
      if (gap > 0) {
        findings.push({
          code: 'INTERNAL_UNINDEXED_PAGE_RUN',
          severity: 'info',
          tier: 'coverage',
          confidence: 1,
          version,
          imagePage: pages[i - 1]! + 1,
          message: `${gap} image page${gap === 1 ? '' : 's'} between indexed pages have no geometry`,
          evidence: { afterImagePage: pages[i - 1], beforeImagePage: pages[i], length: gap },
          autoRepairEligible: false,
        });
      }
    }
  }
  return findings;
}

function fragmentOrdinals(rows: GeometryRow[]): Map<number, number> {
  const placements = buildPagePlacements(rows);
  const out = new Map<number, number>();
  const byVerse = new Map<string, PagePlacement[]>();
  for (const placement of placements.values()) {
    const key = `${placement.row.version}|${placement.row.verseId}`;
    (byVerse.get(key) ?? byVerse.set(key, []).get(key)!)
      .push(placement);
  }
  for (const group of byVerse.values()) {
    group.sort(readingOrder);
    group.forEach((placement, ordinal) => out.set(placement.row.uid, ordinal));
  }
  return out;
}

function mode(values: number[]): number | null {
  if (!values.length) return null;
  const counts = new Map<number, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts].sort((a, b) => b[1] - a[1] || a[0] - b[0])[0]![0];
}

type LinearFit = { intercept: number; slope: number };

function linearFit(points: Array<[number, number]>): LinearFit | null {
  if (points.length < 4) return null;
  const mx = median(points.map(([x]) => x));
  const my = median(points.map(([, y]) => y));
  const usable = points.filter(([x]) => x !== mx);
  const slopes = usable.map(([x, y]) => (y - my) / (x - mx)).filter(Number.isFinite);
  if (!slopes.length) return null;
  const slope = median(slopes);
  return { slope, intercept: median(points.map(([x, y]) => y - slope * x)) };
}

function predict(fit: LinearFit, value: number): number {
  return fit.intercept + fit.slope * value;
}

export function auditFamilies(
  rows: GeometryRow[],
  families: FamilyDefinition[],
): AuditFinding[] {
  const findings: AuditFinding[] = [];
  const ordinals = fragmentOrdinals(rows);
  for (const family of families) {
    const available = family.members.filter((member) => rows.some((row) => row.version === member));
    if (available.length < 2) continue;
    const referenceVersion = available.includes(family.reference ?? '') ? family.reference! : available[0]!;
    const byMemberKey = new Map<string, GeometryRow>();
    const fragmentCounts = new Map<string, number>();
    for (const row of rows.filter((candidate) => available.includes(candidate.version))) {
      const ordinal = ordinals.get(row.uid) ?? 0;
      byMemberKey.set(`${row.version}|${row.verseId}|${ordinal}`, row);
      const countKey = `${row.version}|${row.verseId}`;
      fragmentCounts.set(countKey, Math.max(fragmentCounts.get(countKey) ?? 0, ordinal + 1));
    }
    const verseIds = [...new Set(rows
      .filter((row) => available.includes(row.version))
      .map((row) => row.verseId))];

    for (const verseId of verseIds) {
      const counts = available.map((version) => fragmentCounts.get(`${version}|${verseId}`) ?? 0);
      const majority = mode(counts);
      if (majority == null) continue;
      available.forEach((version, index) => {
        if (available.length === 2) {
          if (index === 0 || counts[0] === counts[1]) return;
        } else if (counts[index] === majority) return;
        const row = byMemberKey.get(`${version}|${verseId}|0`);
        findings.push({
          code: available.length === 2
            ? 'FAMILY_FRAGMENT_COUNT_DISAGREEMENT'
            : 'FAMILY_FRAGMENT_COUNT_MISMATCH',
          severity: 'warning',
          tier: 'statistical',
          confidence: available.length >= 4 ? 0.95 : 0.8,
          version,
          uid: row?.uid,
          verseId,
          page: row?.page,
          imagePage: row?.imagePage,
          message: available.length === 2
            ? `Paired family members disagree on fragment count (${counts[0]} vs ${counts[1]})`
            : `Fragment count ${counts[index]} differs from family mode ${majority}`,
          evidence: {
            family: family.id,
            memberCounts: Object.fromEntries(available.map((m, i) => [m, counts[i]])),
            familyMode: available.length === 2 ? null : majority,
          },
          autoRepairEligible: false,
        });
      });
    }

    const maxOrdinalByVerse = new Map<number, number>();
    for (const verseId of verseIds) {
      maxOrdinalByVerse.set(verseId, Math.max(...available.map((member) => fragmentCounts.get(`${member}|${verseId}`) ?? 0)));
    }
    for (const verseId of verseIds) {
      for (let ordinal = 0; ordinal < (maxOrdinalByVerse.get(verseId) ?? 0); ordinal++) {
        const peers = available
          .map((version) => byMemberKey.get(`${version}|${verseId}|${ordinal}`))
          .filter((row): row is GeometryRow => Boolean(row));
        if (peers.length < 2) continue;
        const pairedFamily = available.length === 2;
        const referencePeer = peers.find((peer) => peer.version === referenceVersion);
        const tlMode = mode(peers.map((row) => Number(notchActive(row.TLW, row.TLH))))!;
        const brMode = mode(peers.map((row) => Number(notchActive(row.BRW, row.BRH))))!;
        const pageDeltas = peers
          .filter((row) => row.version !== referenceVersion)
          .map((row) => {
            const reference = byMemberKey.get(`${referenceVersion}|${verseId}|${ordinal}`);
            return reference ? row.imagePage - reference.imagePage : 0;
          });
        const pageDeltaMode = mode(pageDeltas);
        for (const row of peers) {
          const tl = Number(notchActive(row.TLW, row.TLH));
          const br = Number(notchActive(row.BRW, row.BRH));
          const pairedTarget = pairedFamily && row.version !== referenceVersion;
          const tlDisagrees = pairedFamily
            ? pairedTarget && referencePeer != null &&
              tl !== Number(notchActive(referencePeer.TLW, referencePeer.TLH))
            : tl !== tlMode;
          const brDisagrees = pairedFamily
            ? pairedTarget && referencePeer != null &&
              br !== Number(notchActive(referencePeer.BRW, referencePeer.BRH))
            : br !== brMode;
          if (tlDisagrees) {
            findings.push({
              ...finding(row,
                pairedFamily ? 'FAMILY_TL_TOPOLOGY_DISAGREEMENT' : 'FAMILY_TL_TOPOLOGY_MISMATCH',
                'warning', 'statistical',
                pairedFamily
                  ? 'Top-left notch presence differs between paired family members'
                  : 'Top-left notch presence differs from family consensus',
                {
                  family: family.id,
                  familyMode: pairedFamily ? null : Boolean(tlMode),
                  fragmentOrdinal: ordinal,
                }),
              peers: peers.filter((peer) => peer.uid !== row.uid),
            });
          }
          if (brDisagrees) {
            findings.push({
              ...finding(row,
                pairedFamily ? 'FAMILY_BR_TOPOLOGY_DISAGREEMENT' : 'FAMILY_BR_TOPOLOGY_MISMATCH',
                'warning', 'statistical',
                pairedFamily
                  ? 'Bottom-right notch presence differs between paired family members'
                  : 'Bottom-right notch presence differs from family consensus',
                {
                  family: family.id,
                  familyMode: pairedFamily ? null : Boolean(brMode),
                  fragmentOrdinal: ordinal,
                }),
              peers: peers.filter((peer) => peer.uid !== row.uid),
            });
          }
          if (row.version !== referenceVersion && pageDeltaMode != null) {
            const reference = byMemberKey.get(`${referenceVersion}|${verseId}|${ordinal}`);
            if (reference && row.imagePage - reference.imagePage !== pageDeltaMode) {
              findings.push({
                ...finding(row, 'FAMILY_PAGE_MAPPING_OUTLIER', 'warning', 'statistical',
                  'Image-page relationship differs from the dominant family offset',
                  {
                    family: family.id,
                    referenceVersion,
                    referenceImagePage: reference.imagePage,
                    actualDelta: row.imagePage - reference.imagePage,
                    expectedDelta: pageDeltaMode,
                  }),
                peers: [reference],
              });
            }
          }
        }
      }
    }

    // Page-specific robust affine comparison. A plate mate may be translated
    // or scaled by its scan, but corresponding box edges should follow the
    // same page transform. The median-slope fit is robust to isolated rows and
    // is calculated once per page pair so a corpus audit stays linear.
    for (const targetVersion of available.filter((version) => version !== referenceVersion)) {
      const pairs = [...byMemberKey.entries()]
        .filter(([key, row]) => key.startsWith(`${targetVersion}|`) && row.version === targetVersion)
        .map(([key, target]) => {
          const suffix = key.slice(targetVersion.length + 1);
          const reference = byMemberKey.get(`${referenceVersion}|${suffix}`);
          return reference ? { reference, target } : null;
        })
        .filter((pair): pair is { reference: GeometryRow; target: GeometryRow } => Boolean(pair));
      const byPagePair = new Map<string, typeof pairs>();
      for (const pair of pairs) {
        const key = `${pair.reference.imagePage}|${pair.target.imagePage}`;
        (byPagePair.get(key) ?? byPagePair.set(key, []).get(key)!).push(pair);
      }
      for (const pagePairs of byPagePair.values()) {
        if (pagePairs.length < 6) continue;
        const xFit = linearFit(pagePairs.flatMap(({ reference, target }) => [
          [reference.X, target.X] as [number, number],
          [reference.X + reference.W, target.X + target.W] as [number, number],
        ]));
        const yFit = linearFit(pagePairs.flatMap(({ reference, target }) => [
          [reference.Y, target.Y] as [number, number],
          [reference.Y + reference.H, target.Y + target.H] as [number, number],
        ]));
        if (!xFit || !yFit) continue;
        for (const scored of pagePairs) {
          const residuals = {
            left: scored.target.X - predict(xFit, scored.reference.X),
            right: scored.target.X + scored.target.W - predict(xFit, scored.reference.X + scored.reference.W),
            top: scored.target.Y - predict(yFit, scored.reference.Y),
            bottom: scored.target.Y + scored.target.H - predict(yFit, scored.reference.Y + scored.reference.H),
          };
          const maxResidual = Math.max(...Object.values(residuals).map(Math.abs));
          const scaleTolerance = Math.max(4, scored.target.pageScale * 0.012);
          if (maxResidual > scaleTolerance) {
            findings.push({
              ...finding(scored.target, 'FAMILY_AFFINE_GEOMETRY_OUTLIER', 'warning', 'statistical',
                `Outer geometry misses the page-specific plate transform by ${maxResidual.toFixed(1)} stored units`,
                {
                  family: family.id,
                  referenceVersion,
                  referenceUid: scored.reference.uid,
                  residuals,
                  tolerance: scaleTolerance,
                  xFit,
                  yFit,
                }),
              peers: [scored.reference],
            });
          }
        }
      }

      const exactPairs = pairs.filter(({ reference, target }) =>
        geometryVector(reference).every((value, index) => value === geometryVector(target)[index]));
      if (pairs.length >= 100 && exactPairs.length / pairs.length >= 0.95) {
        const sample = exactPairs[0]!.target;
        findings.push(finding(sample, 'EXACT_GEOMETRY_CLONE', 'warning', 'statistical',
          `${targetVersion} duplicates ${referenceVersion} geometry byte-for-byte for ${exactPairs.length}/${pairs.length} corresponding fragments`,
          { family: family.id, referenceVersion, matchingRows: exactPairs.length, comparedRows: pairs.length }));
      }

      const scaledNotches = pairs.filter(({ reference, target }) => {
        if (!notchActive(reference.TLW, reference.TLH) || !notchActive(target.TLW, target.TLH) ||
            reference.W <= 0 || target.W <= 0) return false;
        return Math.abs(target.TLW - Math.round(reference.TLW * target.W / reference.W)) <= 1;
      });
      const notchedPairs = pairs.filter(({ reference, target }) =>
        notchActive(reference.TLW, reference.TLH) && notchActive(target.TLW, target.TLH));
      if (notchedPairs.length >= 50 && scaledNotches.length / notchedPairs.length >= 0.9) {
        findings.push(finding(scaledNotches[0]!.target, 'MECHANICALLY_SCALED_NOTCHES', 'warning', 'statistical',
          `${targetVersion} top-left notches follow seed width scaling in ${scaledNotches.length}/${notchedPairs.length} cases`,
          { family: family.id, referenceVersion, matchingRows: scaledNotches.length, comparedRows: notchedPairs.length }));
      }
    }
  }
  return findings;
}

export function auditEditionStatistics(rows: GeometryRow[], zThreshold = 7): AuditFinding[] {
  const findings: AuditFinding[] = [];
  const byVersion = new Map<string, GeometryRow[]>();
  for (const row of rows) {
    (byVersion.get(row.version) ?? byVersion.set(row.version, []).get(row.version)!).push(row);
  }
  for (const editionRows of byVersion.values()) {
    const heights = editionRows.map((row) => row.H).filter((value) => value > 0);
    const tlRatios = editionRows.filter((row) => notchActive(row.TLW, row.TLH)).map((row) => row.TLW / row.W);
    const brRatios = editionRows.filter((row) => notchActive(row.BRW, row.BRH)).map((row) => row.BRW / row.W);
    const stats = (population: number[]) => {
      const center = median(population);
      return {
        population,
        center,
        spread: mad(population, center),
        p01: percentile(population, 0.01),
        p99: percentile(population, 0.99),
      };
    };
    const heightStats = stats(heights);
    const tlStats = stats(tlRatios);
    const brStats = stats(brRatios);
    for (const row of editionRows) {
      const metrics: Array<[string, number, ReturnType<typeof stats>]> = [
        ['HEIGHT', row.H, heightStats],
      ];
      if (notchActive(row.TLW, row.TLH) && row.W > 0) metrics.push(['TL_WIDTH_RATIO', row.TLW / row.W, tlStats]);
      if (notchActive(row.BRW, row.BRH) && row.W > 0) metrics.push(['BR_WIDTH_RATIO', row.BRW / row.W, brStats]);
      for (const [name, value, metric] of metrics) {
        if (metric.population.length < 20) continue;
        const z = metric.spread === 0
          ? value === metric.center ? 0 : Number.POSITIVE_INFINITY
          : Math.abs(value - metric.center) / (1.4826 * metric.spread);
        if (z < zThreshold) continue;
        findings.push(finding(row, `EXTREME_${name}`, 'warning', 'statistical',
          `${name.toLowerCase().replaceAll('_', ' ')} is a robust outlier (z=${Number.isFinite(z) ? z.toFixed(1) : '∞'})`,
          {
            value,
            median: metric.center,
            mad: metric.spread,
            robustZ: Number.isFinite(z) ? Number(z.toFixed(3)) : null,
            percentile01: metric.p01,
            percentile99: metric.p99,
          }));
      }
    }
  }
  return findings;
}

export function dedupeFindings(findings: AuditFinding[]): AuditFinding[] {
  const seen = new Set<string>();
  return findings.filter((finding) => {
    const key = `${finding.code}|${finding.version}|${finding.uid ?? ''}|${finding.verseId ?? ''}|${finding.page ?? ''}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
